//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NetworkExtension/NEAgentExtension.h>

#import "NEAgentSessionDelegate-Protocol.h"
#import "NEAppPushPluginDriver-Protocol.h"
#import "NEExtensionAppPushProviderHostDelegate-Protocol.h"

@class NSArray, NSString, NSXPCInterface;

@interface NEAgentAppPushExtension : NEAgentExtension <NEExtensionAppPushProviderHostDelegate, NEAgentSessionDelegate, NEAppPushPluginDriver>
{
}

- (void)sendExtensionFailed;	// IMP=0x0000000100002818
- (void)handleProviderStopped;	// IMP=0x00000001000027b4
- (void)reportIncomingCall:(id)arg1;	// IMP=0x0000000100002724
- (void)handleProviderError:(id)arg1 forMessageID:(id)arg2;	// IMP=0x0000000100002678
- (void)handleProviderError:(id)arg1;	// IMP=0x00000001000025e8
- (void)sendTimerEvent;	// IMP=0x00000001000025a8
- (void)sendOutgoingCallMessage:(id)arg1 andMessageID:(id)arg2;	// IMP=0x00000001000023f4
- (void)setProviderConfiguration:(id)arg1;	// IMP=0x0000000100002388
- (void)stopWithReason:(int)arg1;	// IMP=0x0000000100002294
- (void)startConnectionWithProviderConfig:(id)arg1;	// IMP=0x0000000100002150
- (void)didReceiveIncomingCallWithUserInfo:(id)arg1;	// IMP=0x00000001000020cc
@property(readonly, nonatomic) NSXPCInterface *driverInterface;
@property(readonly, nonatomic) NSXPCInterface *managerInterface;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSArray *uuids;

@end

