//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NEPlugin.h"

#import "NEFilterPluginManager-Protocol.h"

@interface NEFilterPlugin : NEPlugin <NEFilterPluginManager>
{
    long long _filterStatus;	// 64 = 0x40
}

@property(readonly) long long filterStatus; // @synthesize filterStatus=_filterStatus;
- (void)applySettings:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100015904
- (id)managerInterface;	// IMP=0x00000001000158e8
- (id)remotePluginInterface;	// IMP=0x00000001000158cc
- (void)acceptAgentClients;	// IMP=0x0000000100015804
- (void)setStatus:(long long)arg1 error:(id)arg2;	// IMP=0x0000000100015640
- (void)handlePluginFailedWithError:(id)arg1;	// IMP=0x00000001000155e4
- (void)createPacketChannelWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000154b8
- (void)createContentFilterSocketWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001538c
- (void)getFilterClientConnectionWithHandler:(int)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001500c
- (void)startFilter;	// IMP=0x0000000100014fcc

@end

