//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <NetworkExtension/NEPolicySession.h>

@interface NEPolicySession (AlwaysOnVPN)
+ (long long)checkVoiceMailExceptionWithConfiguration:(id)arg1;	// IMP=0x0000000100058980
+ (long long)checkAirPrintExceptionWithConfiguration:(id)arg1;	// IMP=0x00000001000588d0
+ (long long)checkCellularServicesExceptionWithConfiguration:(id)arg1;	// IMP=0x0000000100058820
- (_Bool)addConfigdExceptionWithOrder:(unsigned int *)arg1 policyIDList:(id)arg2;	// IMP=0x000000010005a65c
- (_Bool)evaluateConfigurationEssentialwithOrder:(unsigned int *)arg1;	// IMP=0x000000010005a528
- (_Bool)evaluateConfigurationForHighPriority:(id)arg1 startOrder:(unsigned int)arg2 IMSUseIPSec:(_Bool)arg3 dropAllLevel:(long long *)arg4 captiveNetworkPlugins:(id)arg5;	// IMP=0x000000010005a374
- (_Bool)evaluateConfiguration:(id)arg1 startOrder:(unsigned int)arg2 IMSUseIPSec:(_Bool)arg3 dropAllLevel:(long long *)arg4 captiveNetworkPlugins:(id)arg5;	// IMP=0x000000010005a12c
- (_Bool)addAllowedCaptiveNetworkPlugins:(id)arg1 order:(unsigned int *)arg2 allowCaptiveWebSheet:(_Bool)arg3 allowAllCaptiveNetworkPlugins:(_Bool)arg4 allowedCaptiveNetworkPlugins:(id)arg5;	// IMP=0x000000010005a0a0
- (_Bool)addAllowedCaptiveNetworkPluginsWithResult:(id)arg1 order:(unsigned int *)arg2 allowCaptiveWebSheet:(_Bool)arg3 allowAllCaptiveNetworkPlugins:(_Bool)arg4 allowedCaptiveNetworkPlugins:(id)arg5 result:(id)arg6 policyIDList:(id)arg7;	// IMP=0x0000000100059cf8
- (_Bool)addRegisteredCNP:(id)arg1 order:(unsigned int *)arg2 allowAllCaptiveNetworkPlugins:(_Bool)arg3 allowedCaptiveNetworkPlugins:(id)arg4 result:(id)arg5 policyIDList:(id)arg6;	// IMP=0x0000000100059808
- (_Bool)addServiceExceptionsWithOrder:(unsigned int *)arg1 configuration:(id)arg2 IMSUseIPSec:(_Bool)arg3 dropAllLevel:(long long *)arg4;	// IMP=0x00000001000593c4
- (_Bool)addCellularServicesExceptionPoliciesWithOrder:(unsigned int *)arg1 action:(long long)arg2 useIPSec:(_Bool)arg3 priority:(long long)arg4 primaryPhysicalInterface:(id)arg5 policyIDList:(id)arg6;	// IMP=0x0000000100058b6c
- (_Bool)addCellularServicesExceptionDataWithOrder:(unsigned int *)arg1 action:(long long)arg2 primaryPhysicalInterface:(id)arg3 policyIDList:(id)arg4;	// IMP=0x0000000100058ab4
- (_Bool)addCellularServicesExceptionControlWithOrder:(unsigned int *)arg1 IMSUseIPSec:(_Bool)arg2 action:(long long)arg3 isHighPriority:(_Bool)arg4;	// IMP=0x0000000100058a30
- (_Bool)addPolicyForProcessNoDNSWithOrder:(unsigned int *)arg1 processEUUIDs:(id)arg2 processUUIDs:(id)arg3 includeRealProcess:(_Bool)arg4 pid:(int)arg5 checkEntitlement:(_Bool)arg6 customEntitlement:(id)arg7 checkUID:(_Bool)arg8 uid:(unsigned int)arg9 policyResult:(id)arg10 policyIDList:(id)arg11;	// IMP=0x0000000100058508
- (_Bool)addLocalNetworksExceptionWithOrder:(unsigned int *)arg1 skipOrder:(unsigned int)arg2 priority:(long long)arg3 policyIDList:(id)arg4;	// IMP=0x0000000100058064
- (_Bool)addApplicationExceptionWithOrder:(unsigned int *)arg1 applicationExceptions:(id)arg2 delegateInterfaceName:(id)arg3 priority:(long long)arg4 policyIDList:(id)arg5;	// IMP=0x0000000100057980
- (_Bool)addAirPrintExceptionWithOrder:(unsigned int *)arg1 action:(long long)arg2;	// IMP=0x0000000100057774
- (_Bool)addSharingdExceptionWithOrder:(unsigned int *)arg1 action:(long long)arg2;	// IMP=0x00000001000574f8
- (_Bool)addAPSDExceptionWithOrder:(unsigned int *)arg1 action:(long long)arg2;	// IMP=0x0000000100057340
- (_Bool)addVoiceMailExceptionWithOrder:(unsigned int *)arg1 action:(long long)arg2;	// IMP=0x0000000100057188
- (_Bool)addCommCenterPathPassWithOrder:(unsigned int *)arg1;	// IMP=0x0000000100056d54
- (_Bool)addConfigdWithOrder:(unsigned int *)arg1 needConfigdPassAll:(_Bool)arg2 policyIDList:(id)arg3;	// IMP=0x0000000100056908
- (_Bool)addmDNSResponderWithOrder:(unsigned int *)arg1;	// IMP=0x00000001000565d0
- (_Bool)addSessionManagerWithOrder:(unsigned int *)arg1;	// IMP=0x0000000100056480
- (_Bool)addBonjourWithOrder:(unsigned int *)arg1;	// IMP=0x0000000100056050
- (_Bool)addPortPoliciesWithOrder:(unsigned int *)arg1 appUUID:(id)arg2 port:(id)arg3 local:(_Bool)arg4;	// IMP=0x0000000100055bbc
- (_Bool)addPolicyForProcessDelegatedWithOrder:(unsigned int *)arg1 processEUUIDs:(id)arg2 processUUIDs:(id)arg3 pid:(int)arg4 checkEntitlement:(_Bool)arg5 customEntitlement:(id)arg6 checkUID:(_Bool)arg7 uid:(unsigned int)arg8 policyResult:(id)arg9 policyIDList:(id)arg10;	// IMP=0x00000001000558e0
- (_Bool)addPolicyICMPv6WithOrder:(unsigned int *)arg1 policyResult:(id)arg2 policyIDList:(id)arg3;	// IMP=0x0000000100055608
- (_Bool)addPolicyForDNSWithOrder:(unsigned int *)arg1 processEUUIDs:(id)arg2 scopedInterface:(id)arg3 checkEntitlement:(_Bool)arg4 customEntitlement:(id)arg5 checkUID:(_Bool)arg6 uid:(unsigned int)arg7 policyResult:(id)arg8 policyIDList:(id)arg9;	// IMP=0x000000010005503c
- (_Bool)addPolicyForProcessWithOrder:(unsigned int *)arg1 incrementOrder:(_Bool)arg2 processEUUIDs:(id)arg3 processUUIDs:(id)arg4 pid:(int)arg5 checkEntitlement:(_Bool)arg6 customEntitlement:(id)arg7 checkUID:(_Bool)arg8 uid:(unsigned int)arg9 scopedInterface:(id)arg10 signingIdentifier:(id)arg11 protocol:(unsigned short)arg12 matchDNS:(_Bool)arg13 skipUnscoped:(_Bool)arg14 policyResult:(id)arg15 policyIDList:(id)arg16;	// IMP=0x000000010005497c
- (_Bool)addOnePolicyWithOrder:(unsigned int *)arg1 processEUUIDs:(id)arg2 processUUID:(id)arg3 pid:(int)arg4 checkEntitlement:(_Bool)arg5 customEntitlement:(id)arg6 checkUID:(_Bool)arg7 uid:(unsigned int)arg8 policyResult:(id)arg9 address:(id)arg10 port:(id)arg11 localAddress:(_Bool)arg12 policyIDList:(id)arg13;	// IMP=0x0000000100054454
- (_Bool)addOnePolicyWithOrder:(unsigned int *)arg1 processEUUIDs:(id)arg2 processUUID:(id)arg3 pid:(int)arg4 checkEntitlement:(_Bool)arg5 customEntitlement:(id)arg6 checkUID:(_Bool)arg7 uid:(unsigned int)arg8 dnsUUIDs:(id)arg9 scopedInterface:(id)arg10 signingIdentifier:(id)arg11 protocol:(unsigned short)arg12 policyResult:(id)arg13 policyIDList:(id)arg14;	// IMP=0x0000000100053a98
@end

