//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NESMPowerManagerDelegate-Protocol.h"

@class NEConfiguration, NENetworkAgent, NEOnDemandRule, NEPolicySession, NESMPolicySession, NESMServer, NSArray, NSData, NSDate, NSError, NSMutableArray, NSNumber, NSString, NWMonitor, NWNetworkAgentRegistration, NWResolver;
@protocol OS_dispatch_queue, OS_dispatch_source, OS_os_transaction, OS_xpc_object;

@interface NESMSession : NSObject <NESMPowerManagerDelegate>
{
    NSString *_description;	// 8 = 0x8
    int _lastStopReason;	// 16 = 0x10
    NSError *_lastDisconnectError;	// 24 = 0x18
    _Bool _isOnDemand;	// 32 = 0x20
    _Bool _restartPending;	// 33 = 0x21
    _Bool _disableOnDemand;	// 34 = 0x22
    _Bool _isDropPersistent;	// 35 = 0x23
    int _status;	// 36 = 0x24
    int _type;	// 40 = 0x28
    NSMutableArray *_clients;	// 48 = 0x30
    NSObject<OS_os_transaction> *_activeTransaction;	// 56 = 0x38
    NESMServer *_server;	// 64 = 0x40
    NEConfiguration *_configuration;	// 72 = 0x48
    NSData *_configurationSignature;	// 80 = 0x50
    NSArray *_configurationUserUUIDs;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_queue;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_messageQueue;	// 104 = 0x68
    NSNumber *_uid;	// 112 = 0x70
    NSNumber *_gid;	// 120 = 0x78
    unsigned long long _connectTime;	// 128 = 0x80
    long long _connectCount;	// 136 = 0x88
    long long _connectedCount;	// 144 = 0x90
    long long _disconnectedCount;	// 152 = 0x98
    unsigned long long _maxConnectTime;	// 160 = 0xa0
    NESMPolicySession *_policySession;	// 168 = 0xa8
    long long _failedConnectCountWithinInterval;	// 176 = 0xb0
    NSDate *_firstFailedConnectTime;	// 184 = 0xb8
    NSDate *_lastStatusChangeTime;	// 192 = 0xc0
    NSString *_auxiliaryDataKey;	// 200 = 0xc8
    NEPolicySession *_controlPolicySession;	// 208 = 0xd0
    NEPolicySession *_highPolicySession;	// 216 = 0xd8
    NWNetworkAgentRegistration *_networkAgentRegistration;	// 224 = 0xe0
    NENetworkAgent *_networkAgent;	// 232 = 0xe8
    NWMonitor *_onDemandMonitor;	// 240 = 0xf0
    NEOnDemandRule *_matchedRule;	// 248 = 0xf8
    NSMutableArray *_networkAgentInterfaces;	// 256 = 0x100
    NSArray *_registeredNetworkAgentInterfaces;	// 264 = 0x108
    long long _onDemandPauseLevelInternal;	// 272 = 0x110
    NSObject<OS_dispatch_source> *_onDemandPauseTimerSource;	// 280 = 0x118
    NSMutableArray *_staleOnDemandDNSKeys;	// 288 = 0x120
    NWResolver *_dnsRedirectionDetector;	// 296 = 0x128
    NSObject<OS_os_transaction> *_dnsRedirectionTransaction;	// 304 = 0x130
    NSString *_lastPrimaryInterface;	// 312 = 0x138
    NSMutableArray *_onDemandDomainCache;	// 320 = 0x140
    NSObject<OS_xpc_object> *_startMessage;	// 328 = 0x148
    long long _defaultDropType;	// 336 = 0x150
}

+ (struct __CFDictionary *)copyDefaultRouteCacheIsIPv6:(_Bool)arg1;	// IMP=0x000000010009364c
+ (struct __CFDictionary *)copyRouteCacheFromRoutes:(struct __CFArray *)arg1 isIPv6:(_Bool)arg2;	// IMP=0x0000000100093640
+ (id)sessionWithConfiguration:(id)arg1 andType:(int)arg2 andServer:(id)arg3;	// IMP=0x000000010008e1e0
- (void).cxx_destruct;	// IMP=0x0000000100093dcc
@property _Bool isDropPersistent; // @synthesize isDropPersistent=_isDropPersistent;
@property long long defaultDropType; // @synthesize defaultDropType=_defaultDropType;
@property _Bool disableOnDemand; // @synthesize disableOnDemand=_disableOnDemand;
@property(retain) NSObject<OS_xpc_object> *startMessage; // @synthesize startMessage=_startMessage;
@property _Bool restartPending; // @synthesize restartPending=_restartPending;
@property(retain) NSMutableArray *onDemandDomainCache; // @synthesize onDemandDomainCache=_onDemandDomainCache;
@property(retain) NSString *lastPrimaryInterface; // @synthesize lastPrimaryInterface=_lastPrimaryInterface;
@property(retain) NSObject<OS_os_transaction> *dnsRedirectionTransaction; // @synthesize dnsRedirectionTransaction=_dnsRedirectionTransaction;
@property(retain) NWResolver *dnsRedirectionDetector; // @synthesize dnsRedirectionDetector=_dnsRedirectionDetector;
@property(retain) NSMutableArray *staleOnDemandDNSKeys; // @synthesize staleOnDemandDNSKeys=_staleOnDemandDNSKeys;
@property NSObject<OS_dispatch_source> *onDemandPauseTimerSource; // @synthesize onDemandPauseTimerSource=_onDemandPauseTimerSource;
@property long long onDemandPauseLevelInternal; // @synthesize onDemandPauseLevelInternal=_onDemandPauseLevelInternal;
@property(retain) NSArray *registeredNetworkAgentInterfaces; // @synthesize registeredNetworkAgentInterfaces=_registeredNetworkAgentInterfaces;
@property(retain) NSMutableArray *networkAgentInterfaces; // @synthesize networkAgentInterfaces=_networkAgentInterfaces;
@property(retain) NEOnDemandRule *matchedRule; // @synthesize matchedRule=_matchedRule;
@property(retain) NWMonitor *onDemandMonitor; // @synthesize onDemandMonitor=_onDemandMonitor;
@property(retain) NENetworkAgent *networkAgent; // @synthesize networkAgent=_networkAgent;
@property(retain) NWNetworkAgentRegistration *networkAgentRegistration; // @synthesize networkAgentRegistration=_networkAgentRegistration;
@property(retain) NEPolicySession *highPolicySession; // @synthesize highPolicySession=_highPolicySession;
@property(retain) NEPolicySession *controlPolicySession; // @synthesize controlPolicySession=_controlPolicySession;
@property(retain) NSString *auxiliaryDataKey; // @synthesize auxiliaryDataKey=_auxiliaryDataKey;
@property(retain) NSDate *lastStatusChangeTime; // @synthesize lastStatusChangeTime=_lastStatusChangeTime;
@property(retain) NSDate *firstFailedConnectTime; // @synthesize firstFailedConnectTime=_firstFailedConnectTime;
@property long long failedConnectCountWithinInterval; // @synthesize failedConnectCountWithinInterval=_failedConnectCountWithinInterval;
@property(retain) NESMPolicySession *policySession; // @synthesize policySession=_policySession;
@property unsigned long long maxConnectTime; // @synthesize maxConnectTime=_maxConnectTime;
@property long long disconnectedCount; // @synthesize disconnectedCount=_disconnectedCount;
@property long long connectedCount; // @synthesize connectedCount=_connectedCount;
@property long long connectCount; // @synthesize connectCount=_connectCount;
@property unsigned long long connectTime; // @synthesize connectTime=_connectTime;
@property _Bool isOnDemand; // @synthesize isOnDemand=_isOnDemand;
@property(retain) NSNumber *gid; // @synthesize gid=_gid;
@property(retain, nonatomic, setter=setUID:) NSNumber *uid; // @synthesize uid=_uid;
@property(readonly) NSObject<OS_dispatch_queue> *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) NSArray *configurationUserUUIDs; // @synthesize configurationUserUUIDs=_configurationUserUUIDs;
@property(retain) NSData *configurationSignature; // @synthesize configurationSignature=_configurationSignature;
@property(retain) NEConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly) NESMServer *server; // @synthesize server=_server;
@property(readonly) int type; // @synthesize type=_type;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain) NSObject<OS_os_transaction> *activeTransaction; // @synthesize activeTransaction=_activeTransaction;
@property(readonly) NSMutableArray *clients; // @synthesize clients=_clients;
- (id)getIDSNetworkAgentDomain;	// IMP=0x0000000100093a7c
- (_Bool)hasProviderWithBundleIdentifier:(id)arg1;	// IMP=0x0000000100093a74
- (void)checkPluginInstalledWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100093a64
- (void)startWithCommand:(id)arg1 isOnDemand:(_Bool)arg2;	// IMP=0x000000010009381c
- (void)invalidate;	// IMP=0x0000000100093808
- (void)handleCaptiveNetworkPluginsChanged;	// IMP=0x0000000100093804
- (void)handleNetworkDetectionNotification:(int)arg1;	// IMP=0x0000000100093800
- (void)handleInstalledAppsChanged;	// IMP=0x00000001000937fc
- (void)handleNetworkConfigurationChange:(long long)arg1;	// IMP=0x00000001000937f8
@property(readonly) _Bool isActive;
@property(readonly) NSString *pluginType;
- (void)stopIfNecessaryWithReason:(int)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100093584
- (void)stopIfNecessaryWithReason:(int)arg1;	// IMP=0x0000000100093260
- (void)uninstall;	// IMP=0x000000010009325c
- (void)uninstallOnQueue;	// IMP=0x00000001000931d0
- (void)installPended;	// IMP=0x00000001000931cc
- (void)installPendedOnQueue;	// IMP=0x0000000100093140
- (void)install;	// IMP=0x000000010009313c
- (void)installWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100093044
- (_Bool)handleUpdateConfiguration:(id)arg1;	// IMP=0x0000000100092e60
- (void)handleUpdateConfiguration:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100092528
@property(readonly) int SCNCStatus;
- (void)setupFromAuxiliaryData;	// IMP=0x00000001000923a8
@property(retain) NSError *lastDisconnectError;
@property int lastStopReason;
- (_Bool)handleAgentClientConnection:(id)arg1 WithMessage:(id)arg2;	// IMP=0x0000000100091fb0
- (_Bool)shouldBeIdleForStatus:(int)arg1;	// IMP=0x0000000100091628
- (void)notifyChangedExtendedStatus;	// IMP=0x00000001000914b4
- (void)prepareNetwork;	// IMP=0x00000001000912a8
- (void)satisfyPathResult:(id)arg1;	// IMP=0x00000001000911e0
- (void)handleNetworkPrepareResult:(id)arg1;	// IMP=0x00000001000910ec
- (id)copyExtendedStatus;	// IMP=0x0000000100090da4
- (void)handleSendInfoMessage:(id)arg1 withType:(int)arg2;	// IMP=0x0000000100090da0
- (void)handleGetInfoMessage:(id)arg1 withType:(int)arg2;	// IMP=0x0000000100090d9c
- (void)handleSecuritySessionInfoRequest:(id)arg1;	// IMP=0x0000000100090d98
- (void)handleChangeEventForFallback:(_Bool)arg1;	// IMP=0x0000000100090d94
- (void)handleChangeEventForFallbackInterfaces:(id)arg1;	// IMP=0x0000000100090d90
- (void)handleChangeEventForInterface:(id)arg1 newFlags:(unsigned long long)arg2 previousFlags:(unsigned long long)arg3;	// IMP=0x0000000100090ae0
- (void)handleDeviceUnlock;	// IMP=0x0000000100090adc
- (void)handleDeviceLock;	// IMP=0x0000000100090ad8
- (void)handleUserLogin;	// IMP=0x0000000100090ad4
- (void)handleUserLogout;	// IMP=0x0000000100090ad0
- (void)handleUserSwitch;	// IMP=0x0000000100090acc
- (void)handleWakeup;	// IMP=0x0000000100090ac8
- (void)handleSleepTime:(double)arg1;	// IMP=0x0000000100090ac4
- (_Bool)handleSleep;	// IMP=0x0000000100090abc
- (_Bool)canSleep;	// IMP=0x0000000100090ab4
- (void)handleEstablishIPCMessage:(id)arg1;	// IMP=0x0000000100090ab0
- (void)handleStopMessageWithReason:(int)arg1;	// IMP=0x0000000100090a48
- (void)handleStartMessage:(id)arg1;	// IMP=0x000000010009061c
- (_Bool)startMessageStopCurrentSession:(id)arg1;	// IMP=0x00000001000905a4
- (_Bool)startMessageIsOnDemand:(id)arg1;	// IMP=0x000000010009052c
- (void)handleGetStatusMessage:(id)arg1;	// IMP=0x000000010009049c
- (void)handleInitializeState;	// IMP=0x0000000100090498
- (void)handleCommand:(id)arg1 fromClient:(id)arg2;	// IMP=0x000000010008fb5c
- (void)registerSession:(id)arg1 fromClient:(id)arg2;	// IMP=0x000000010008f804
- (void)removeAllClients;	// IMP=0x000000010008f5d0
- (void)addClientConnection:(id)arg1;	// IMP=0x000000010008f00c
- (id)description;	// IMP=0x000000010008f004
- (void)dealloc;	// IMP=0x000000010008eea8
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2;	// IMP=0x000000010008ee44
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2 sessionQueue:(id)arg3 messageQueue:(id)arg4;	// IMP=0x000000010008ebe4
- (void)uninstallStaleDNSConfigurations;	// IMP=0x00000001000799c8
- (int)installDNSServers:(id)arg1 forService:(id)arg2;	// IMP=0x00000001000796cc
- (void)storeCurrentDNSConfigurationsForServiceID:(id)arg1;	// IMP=0x0000000100079590
- (int)nextDNSServiceID;	// IMP=0x0000000100079550
- (void)setOnDemandPauseLevel:(long long)arg1;	// IMP=0x00000001000791c8
- (long long)onDemandPauseLevel;	// IMP=0x00000001000791bc
- (void)handlePrimaryInterfaceChange;	// IMP=0x00000001000791b0
- (void)removeOnDemandObserver;	// IMP=0x0000000100079110
- (void)resetOnDemandConfigurationForce:(_Bool)arg1;	// IMP=0x00000001000789c0
- (id)copyDisconnectRulesFromRules:(id)arg1;	// IMP=0x00000001000788ec
@property(readonly) _Bool isDisconnectOnDemandEnabled;
@property(readonly) _Bool isOnDemandEnabled;
- (id)networkDescriptionsForOnDemandRules;	// IMP=0x00000001000780ec
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100077848
- (void)setupDomainCacheForEvaluateConnectionRule:(id)arg1;	// IMP=0x0000000100076b94
- (void)updateDomainCache;	// IMP=0x00000001000769dc
- (void)startDNSRedirectionDetection;	// IMP=0x00000001000764d4
- (void)removeDNSRedirectionDetector;	// IMP=0x0000000100076434
- (void)clearDomainCache;	// IMP=0x0000000100076318
- (void)resetOnDemandPolicies;	// IMP=0x0000000100075964
- (id)fetchCriticalOnDemandDomains;	// IMP=0x00000001000758b8
- (void)clearNetworkAgentInterfaceNames;	// IMP=0x0000000100075798
- (void)removeNetworkAgentInterfaceName:(id)arg1;	// IMP=0x000000010007563c
- (void)addNetworkAgentInterfaceName:(id)arg1;	// IMP=0x000000010007544c
- (void)resetNetworkAgent;	// IMP=0x0000000100073df4
- (void)removeNetworkAgent;	// IMP=0x0000000100073ca8
- (void)removeOnDemandTimerSource;	// IMP=0x0000000100073c1c
- (void)resetNetworkAgentFileHandle;	// IMP=0x00000001000735f0
- (void)setupNetworkAgent;	// IMP=0x0000000100072bf4
- (void)setAssertionHandlersOnAgent:(id)arg1;	// IMP=0x00000001000728b0
- (void)setStartHandlerOnAgent:(id)arg1;	// IMP=0x000000010007266c

@end

