//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMVPNSessionState.h"

@interface NESMVPNSessionStateStopping : NESMVPNSessionState
{
}

- (void)handlePlugin:(id)arg1 didStartWithPID:(int)arg2 error:(id)arg3;	// IMP=0x000000010006b71c
- (void)handleEstablishIPC;	// IMP=0x000000010006b5e4
- (void)handleTimeout;	// IMP=0x000000010006b4f4
- (void)handlePlugin:(id)arg1 statusDidChangeToDisconnectedWithReason:(int)arg2;	// IMP=0x000000010006b368
- (void)handleClearConfigurationResult:(_Bool)arg1;	// IMP=0x000000010006b080
- (_Bool)handleClearConfiguration;	// IMP=0x000000010006af7c
- (void)handleSetConfigurationResult:(_Bool)arg1;	// IMP=0x000000010006ae7c
- (_Bool)handleSetConfiguration;	// IMP=0x000000010006ad78
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010006ad08
- (id)init;	// IMP=0x000000010006accc

@end

