//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMFilterSessionState.h"

@interface NESMFilterSessionStateRunning : NESMFilterSessionState
{
}

- (void)handleUpdateConfiguration;	// IMP=0x000000010005c394
- (void)handleWakeup;	// IMP=0x000000010005c2a4
- (_Bool)handleSleep;	// IMP=0x000000010005c1b0
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010005c0e4
- (id)init;	// IMP=0x000000010005c0a8

@end

