//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMSession.h"

@class NSMutableArray, NWInterface;

@interface NESMIKEv2VPNFallbackSession : NESMSession
{
    _Bool _fallbackIsActive;	// 8 = 0x8
    int _sleepAckCount;	// 12 = 0xc
    NSMutableArray *_childSessions;	// 16 = 0x10
    unsigned long long _predicatedInterfaceIndex;	// 24 = 0x18
    unsigned long long _advisoryInterfaceIndex;	// 32 = 0x20
    NWInterface *_primaryCellularInterface;	// 40 = 0x28
    unsigned long long _cellularIfFlags;	// 48 = 0x30
    long long _installState;	// 56 = 0x38
    NSMutableArray *_configurationOperationArray;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100087bf0
@property(retain) NSMutableArray *configurationOperationArray; // @synthesize configurationOperationArray=_configurationOperationArray;
@property _Bool fallbackIsActive; // @synthesize fallbackIsActive=_fallbackIsActive;
@property int sleepAckCount; // @synthesize sleepAckCount=_sleepAckCount;
@property long long installState; // @synthesize installState=_installState;
@property unsigned long long cellularIfFlags; // @synthesize cellularIfFlags=_cellularIfFlags;
@property(retain) NWInterface *primaryCellularInterface; // @synthesize primaryCellularInterface=_primaryCellularInterface;
@property unsigned long long advisoryInterfaceIndex; // @synthesize advisoryInterfaceIndex=_advisoryInterfaceIndex;
@property unsigned long long predicatedInterfaceIndex; // @synthesize predicatedInterfaceIndex=_predicatedInterfaceIndex;
@property(retain) NSMutableArray *childSessions; // @synthesize childSessions=_childSessions;
- (void)startFallbackSession;	// IMP=0x00000001000875b8
- (void)resetFallbackInterfaceOnServer;	// IMP=0x0000000100086f50
- (void)handleClearConfigurationResult:(id)arg1;	// IMP=0x0000000100086c80
- (void)handleSetConfigurationResult:(id)arg1 tunnelInterfaceName:(id)arg2;	// IMP=0x0000000100086a1c
- (_Bool)shouldDisableInitialContactForSession:(id)arg1;	// IMP=0x00000001000867d0
- (void)handleNetworkConfigurationChange:(long long)arg1;	// IMP=0x00000001000864d8
- (void)uninstall;	// IMP=0x000000010008604c
- (void)requestUninstall:(id)arg1;	// IMP=0x0000000100085d38
- (void)requestUninstall;	// IMP=0x000000010008570c
- (void)installPended;	// IMP=0x0000000100085290
- (void)install;	// IMP=0x0000000100084b3c
- (void)registerSession:(id)arg1 fromClient:(id)arg2 fromSession:(id)arg3;	// IMP=0x00000001000845d4
- (void)requestInstallForSession:(id)arg1 exclusive:(_Bool)arg2;	// IMP=0x00000001000842a4
- (void)requestInstall;	// IMP=0x0000000100083b7c
- (void)setLastDisconnectErrorFromSession:(id)arg1 lastDisconnectError:(id)arg2;	// IMP=0x0000000100083968
- (void)setLastStopReasonFromSession:(id)arg1 lastStopReason:(int)arg2;	// IMP=0x000000010008377c
- (void)setStatusFromSession:(id)arg1 andStatus:(int)arg2;	// IMP=0x0000000100083368
- (void)setStatus:(int)arg1;	// IMP=0x0000000100083100
- (int)parentStatus:(int)arg1 secondStatus:(int)arg2;	// IMP=0x0000000100082ef4
- (void)prepareNetwork:(id)arg1;	// IMP=0x000000010008294c
- (void)handleNetworkDetectionNotification:(int)arg1;	// IMP=0x0000000100082650
- (void)handleChangeEventForInterface:(id)arg1 newFlags:(unsigned long long)arg2 previousFlags:(unsigned long long)arg3;	// IMP=0x0000000100082444
- (id)copyExtendedStatus;	// IMP=0x0000000100081d60
- (id)copyStatistics;	// IMP=0x000000010008170c
- (void)handleGetInfoMessage:(id)arg1 withType:(int)arg2;	// IMP=0x000000010008163c
- (_Bool)handleUpdateConfiguration:(id)arg1;	// IMP=0x0000000100080bf0
- (void)ackSleep:(id)arg1;	// IMP=0x0000000100080ad8
- (void)handleUserSwitch;	// IMP=0x0000000100080800
- (void)handleUserLogout;	// IMP=0x0000000100080528
- (void)handleSleepTime:(double)arg1;	// IMP=0x0000000100080234
- (_Bool)handleSleep;	// IMP=0x000000010007ff10
- (void)handleWakeup;	// IMP=0x000000010007fc38
- (void)handleStopMessageWithReason:(int)arg1;	// IMP=0x000000010007f91c
- (void)handleStartMessage:(id)arg1;	// IMP=0x000000010007f6d4
- (void)handleInitializeState;	// IMP=0x000000010007f3dc
- (id)tunnelInstallState2String:(long long)arg1;	// IMP=0x000000010007f37c
- (id)tunnelSessionType2String:(id)arg1;	// IMP=0x000000010007f23c
- (int)type;	// IMP=0x000000010007f234
- (void)dealloc;	// IMP=0x000000010007f1bc
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010007ea3c
- (_Bool)startMonitoringPrimaryCellularInterface;	// IMP=0x000000010007e880
- (void)handleChangeEventForFallback:(_Bool)arg1;	// IMP=0x000000010007e6b8
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2 andProtocol:(id)arg3 andSessionType:(int)arg4;	// IMP=0x000000010007e270

@end

