//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMFlowDivertSession.h"

@interface NESMTransparentProxySession : NESMFlowDivertSession
{
}

- (void)addDefaultDropPolicyForPluginUUIDs:(id)arg1;	// IMP=0x000000010007a1e8
- (void)plugin:(id)arg1 didStartWithPID:(int)arg2 error:(id)arg3;	// IMP=0x000000010007a0d0
- (void)setConfigurationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100079a74

@end

