//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMVPNSessionState.h"

@interface NESMVPNSessionStatePreparingNetwork : NESMVPNSessionState
{
}

- (void)handleNetworkPrepareResult:(id)arg1;	// IMP=0x0000000100068ce8
- (void)enterWithSession:(id)arg1;	// IMP=0x0000000100068c64
- (id)init;	// IMP=0x0000000100068c28

@end

