//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCAirPlaySecurityPayload.h>

@interface MCAirPlaySecurityPayload (Daemon)
- (id)handlerWithProfileHandler:(id)arg1;	// IMP=0x000000010006df28
@end

