//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@interface MCAirPlayPayloadHandler : MCNewPayloadHandler
{
}

+ (void)recomputeAirPlaySettings;	// IMP=0x000000010007389c
- (void)unsetAside;	// IMP=0x0000000100073890
- (void)remove;	// IMP=0x000000010007381c
- (void)setAside;	// IMP=0x0000000100073810
- (void)_removeDependency;	// IMP=0x00000001000734bc
- (void)_addDependency;	// IMP=0x0000000100073168
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100072dac

@end

