//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCProfileServiceServer;
@protocol OS_dispatch_queue;

@interface MCBackgroundActivityManager : NSObject
{
    int _profileChangeNotificationToken;	// 8 = 0x8
    int _managedAppChangeNotificationToken;	// 12 = 0xc
    int _effectiveSettingsChangedNotificationToken;	// 16 = 0x10
    MCProfileServiceServer *_server;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_workQueue;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100019370
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) int effectiveSettingsChangedNotificationToken; // @synthesize effectiveSettingsChangedNotificationToken=_effectiveSettingsChangedNotificationToken;
@property(nonatomic) int managedAppChangeNotificationToken; // @synthesize managedAppChangeNotificationToken=_managedAppChangeNotificationToken;
@property(nonatomic) int profileChangeNotificationToken; // @synthesize profileChangeNotificationToken=_profileChangeNotificationToken;
@property(nonatomic) __weak MCProfileServiceServer *server; // @synthesize server=_server;
- (void)_workQueueReschedule:(long long)arg1 startDate:(id)arg2 gracePeriod:(id)arg3 priority:(const char *)arg4 repeatingInterval:(id)arg5;	// IMP=0x0000000100019218
- (void)_rescheduleBackgroundActivity:(long long)arg1 startDate:(id)arg2 gracePeriod:(id)arg3 priority:(const char *)arg4 repeatingInterval:(id)arg5;	// IMP=0x00000001000190b0
- (void)rescheduleManagedAppValidationJob:(id)arg1;	// IMP=0x0000000100019090
- (void)rescheduleManagedAppValidationJob;	// IMP=0x0000000100019024
- (void)rescheduleProfileJanitorJob;	// IMP=0x0000000100018f84
- (void)_handleXPCActivity:(long long)arg1 proposedStartDate:(id)arg2 normalizeStartDate:(_Bool)arg3 proposedGracePeriod:(id)arg4 proposedPriority:(const char *)arg5 repeatingInterval:(id)arg6 requireNetwork:(_Bool)arg7;	// IMP=0x00000001000187f8
- (id)_jobDescriptionForBackgroundActivityType:(long long)arg1;	// IMP=0x00000001000187bc
- (const char *)_jobNameForBackgroundActivityType:(long long)arg1;	// IMP=0x0000000100018794
- (id)_nextManagedAppValidationDateWithOverride:(id)arg1;	// IMP=0x00000001000186fc
- (id)_nextActivationLockCleanupDate;	// IMP=0x000000010001867c
- (id)_profileJanitorEarliestExpiryDate;	// IMP=0x0000000100018630
- (id)_nextRegularDate;	// IMP=0x0000000100018468
- (void)activationLockBypassCodeWasStored:(id)arg1;	// IMP=0x0000000100018374
- (void)stop;	// IMP=0x0000000100018300
- (void)start;	// IMP=0x0000000100017d94

@end

