//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewPayloadHandler.h"

@class NSDictionary;

@interface MCGmailAccountPayloadHandler : MCNewPayloadHandler
{
    NSDictionary *_setAsideAccountDictionary;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100071f6c
@property(retain, nonatomic) NSDictionary *setAsideAccountDictionary; // @synthesize setAsideAccountDictionary=_setAsideAccountDictionary;
- (void)unsetAside;	// IMP=0x0000000100071eb8
- (void)setAside;	// IMP=0x0000000100071bc0
- (void)remove;	// IMP=0x0000000100071b10
- (void)_remove;	// IMP=0x0000000100071548
- (_Bool)isInstalled;	// IMP=0x0000000100071308
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0000000100070f34
- (id)_installWithAccountDictionary:(id)arg1;	// IMP=0x0000000100070a64
- (id)accountDictionaryWithIsInstalledByMDM:(_Bool)arg1 personaID:(id)arg2;	// IMP=0x00000001000706c4
- (id)MCACAccountIdentifier;	// IMP=0x0000000100070670
- (id)unhashedAccountIdentifier;	// IMP=0x00000001000705cc
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x000000010007055c

@end

