//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCNewCertificatePayloadHandler.h"

@interface MCNewWAPIIdentityCertificatePayloadHandler : MCNewCertificatePayloadHandler
{
}

- (void)remove;	// IMP=0x000000010006d79c
- (void)unsetAside;	// IMP=0x000000010006d6fc
- (void)setAside;	// IMP=0x000000010006d5e8
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x000000010006d274
- (_Bool)_storePEMDataInKeychain:(id)arg1 UUID:(id)arg2 outError:(id *)arg3;	// IMP=0x000000010006cfa8
- (id)_cannotStoreCertificateError;	// IMP=0x000000010006cec8
- (id)_cannotStorePEMDataError;	// IMP=0x000000010006cde8
- (id)_malformedCertificateError;	// IMP=0x000000010006cd08

@end

