//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (MCUtilities)
- (void)MCFilterRestrictionPayloadKeys:(id)arg1;	// IMP=0x0000000100015b1c
- (void)MCSetUnionSetting:(id)arg1 values:(id)arg2;	// IMP=0x0000000100015818
- (void)MCSetIntersectionSetting:(id)arg1 values:(id)arg2;	// IMP=0x0000000100015514
- (void)MCSetUnionRestriction:(id)arg1 values:(id)arg2;	// IMP=0x0000000100015210
- (void)MCSetIntersectionRestriction:(id)arg1 values:(id)arg2;	// IMP=0x0000000100014f0c
- (void)MCSetValueRestriction:(id)arg1 value:(id)arg2;	// IMP=0x0000000100014bcc
- (void)MCDeleteBoolRestriction:(id)arg1;	// IMP=0x0000000100014b14
- (void)MCSetBoolRestriction:(id)arg1 value:(_Bool)arg2;	// IMP=0x0000000100014838
- (void)MCSetObjectIfNotNil:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001000147e4
- (void)MCDeepCopyMissingEntriesFromDictionary:(id)arg1;	// IMP=0x00000001000145a4
- (void)MCDeepCopyEntriesFromDictionary:(id)arg1;	// IMP=0x0000000100014368
@end

