/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:51 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/Network.framework/Network
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_nw_advertise_descriptor;
#import <Network/Network-Structs.h>
@class NSObject, NSString, NSData;

@interface NWAdvertiseDescriptor : NSObject {

	NSObject*<OS_nw_advertise_descriptor> _internalDescriptor;

}

@property (nonatomic,retain) NSObject*<OS_nw_advertise_descriptor> internalDescriptor;              //@synthesize internalDescriptor=_internalDescriptor - In the implementation block
@property (nonatomic,readonly) NSString * bonjourServiceDomain; 
@property (nonatomic,readonly) NSString * bonjourServiceType; 
@property (nonatomic,readonly) NSString * bonjourServiceName; 
@property (nonatomic,retain) NSData * txtRecord; 
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(NSData *)txtRecord;
-(void)setTxtRecord:(NSData *)arg1 ;
-(id)initWithDescriptor:(id)arg1 ;
-(id)privateDescription;
-(NSString *)bonjourServiceType;
-(id)descriptionWithIndent:(int)arg1 showFullContent:(BOOL)arg2 ;
-(id)initWithName:(id)arg1 type:(id)arg2 domain:(id)arg3 ;
-(NSString *)bonjourServiceDomain;
-(NSString *)bonjourServiceName;
-(NSObject*<OS_nw_advertise_descriptor>)internalDescriptor;
-(void)setInternalDescriptor:(NSObject*<OS_nw_advertise_descriptor>)arg1 ;
@end

