/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:50 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/Network.framework/Network
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Network/Network-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSMutableArray;

@interface NWAWDNWDurationAccumulation : PBCodable <NSCopying> {

	NSString* _name;
	NSMutableArray* _states;

}

@property (nonatomic,readonly) BOOL hasName; 
@property (nonatomic,retain) NSString * name;                      //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSMutableArray * states;              //@synthesize states=_states - In the implementation block
+(Class)statesType;
-(NSString *)name;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(void)setName:(NSString *)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasName;
-(void)setStates:(NSMutableArray *)arg1 ;
-(void)addStates:(id)arg1 ;
-(unsigned long long)statesCount;
-(void)clearStates;
-(id)statesAtIndex:(unsigned long long)arg1 ;
-(NSMutableArray *)states;
@end

