/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:51 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/Network.framework/Network
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Network/Network-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NWPBInterface : PBCodable <NSCopying> {

	unsigned _delegateIndex;
	unsigned _generation;
	unsigned _index;
	unsigned _mtu;
	NSString* _name;
	int _subtype;
	int _type;
	BOOL _expensive;
	SCD_Struct_NW33 _has;

}

@property (assign,nonatomic) BOOL hasType; 
@property (assign,nonatomic) int type;                            //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL hasSubtype; 
@property (assign,nonatomic) int subtype;                         //@synthesize subtype=_subtype - In the implementation block
@property (nonatomic,readonly) BOOL hasName; 
@property (nonatomic,retain) NSString * name;                     //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) BOOL hasIndex; 
@property (assign,nonatomic) unsigned index;                      //@synthesize index=_index - In the implementation block
@property (assign,nonatomic) BOOL hasGeneration; 
@property (assign,nonatomic) unsigned generation;                 //@synthesize generation=_generation - In the implementation block
@property (assign,nonatomic) BOOL hasDelegateIndex; 
@property (assign,nonatomic) unsigned delegateIndex;              //@synthesize delegateIndex=_delegateIndex - In the implementation block
@property (assign,nonatomic) BOOL hasMtu; 
@property (assign,nonatomic) unsigned mtu;                        //@synthesize mtu=_mtu - In the implementation block
@property (assign,nonatomic) BOOL hasExpensive; 
@property (assign,nonatomic) BOOL expensive;                      //@synthesize expensive=_expensive - In the implementation block
-(NSString *)name;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(void)setType:(int)arg1 ;
-(int)type;
-(void)setName:(NSString *)arg1 ;
-(unsigned)index;
-(id)dictionaryRepresentation;
-(unsigned)generation;
-(int)subtype;
-(void)setIndex:(unsigned)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasName;
-(void)setHasType:(BOOL)arg1 ;
-(BOOL)hasType;
-(id)typeAsString:(int)arg1 ;
-(int)StringAsType:(id)arg1 ;
-(void)setSubtype:(int)arg1 ;
-(unsigned)mtu;
-(void)setHasIndex:(BOOL)arg1 ;
-(BOOL)hasIndex;
-(BOOL)expensive;
-(void)setMtu:(unsigned)arg1 ;
-(void)setGeneration:(unsigned)arg1 ;
-(void)setHasSubtype:(BOOL)arg1 ;
-(BOOL)hasSubtype;
-(id)subtypeAsString:(int)arg1 ;
-(int)StringAsSubtype:(id)arg1 ;
-(void)setHasGeneration:(BOOL)arg1 ;
-(BOOL)hasGeneration;
-(void)setDelegateIndex:(unsigned)arg1 ;
-(void)setHasDelegateIndex:(BOOL)arg1 ;
-(BOOL)hasDelegateIndex;
-(void)setHasMtu:(BOOL)arg1 ;
-(BOOL)hasMtu;
-(void)setExpensive:(BOOL)arg1 ;
-(void)setHasExpensive:(BOOL)arg1 ;
-(BOOL)hasExpensive;
-(unsigned)delegateIndex;
@end

