/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:51 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/Network.framework/Network
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUUID, NWBrowser;

@interface NWRemoteBrowserWrapper : NSObject {

	NSUUID* _clientID;
	NWBrowser* _browser;

}

@property (retain) NSUUID * clientID;                //@synthesize clientID=_clientID - In the implementation block
@property (retain) NWBrowser * browser;              //@synthesize browser=_browser - In the implementation block
-(NSUUID *)clientID;
-(void)setClientID:(NSUUID *)arg1 ;
-(NWBrowser *)browser;
-(void)setBrowser:(NWBrowser *)arg1 ;
@end

