//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NEHelperDelegate-Protocol.h"

@class NSString;

@interface NEHelperHotspotConfigurationManager : NSObject <NEHelperDelegate>
{
    NSString *_bundleID;	// 8 = 0x8
}

+ (void)checkAppForConfigurationCleanup:(id)arg1;	// IMP=0x0000000100004150
+ (_Bool)verifyEntitlement:(id)arg1;	// IMP=0x0000000100002088
+ (void)initGlobals;	// IMP=0x0000000100001fa0
- (void).cxx_destruct;	// IMP=0x00000001000042d0
@property(readonly) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void)handleMessage:(id)arg1;	// IMP=0x0000000100003fd0
- (_Bool)processRequest:(id)arg1;	// IMP=0x0000000100003f5c
- (_Bool)processQueryNetworks:(id)arg1;	// IMP=0x0000000100003d20
- (_Bool)processRemoveConfigurationRequest:(id)arg1;	// IMP=0x0000000100003c1c
- (void)removeWiFiNetworkConfiguration:(id)arg1;	// IMP=0x0000000100003958
- (_Bool)checkIfJoinOnceNetworkAndDisassociate:(struct __WiFiManagerClient *)arg1;	// IMP=0x00000001000037d8
- (_Bool)processAddConfigurationRequest:(id)arg1;	// IMP=0x0000000100003108
- (_Bool)checkIfSystemAppOrDaemon;	// IMP=0x0000000100002fb4
- (struct __WiFiNetwork *)createWiFiNetworkFromConfiguration:(id)arg1;	// IMP=0x00000001000028c4
- (id)createEAPClientConfiguration:(id)arg1;	// IMP=0x0000000100002398
- (id)getTTLSInnerAuthenticationString:(long long)arg1;	// IMP=0x0000000100002340
@property(readonly, nonatomic) NSString *name;
- (id)initWithFirstMessage:(id)arg1;	// IMP=0x00000001000021cc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

