//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NEHelperDelegate-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface NEHelperCacheManager : NSObject <NEHelperDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    struct __SCPreferences *_prefs;	// 16 = 0x10
}

+ (id)sharedManager;	// IMP=0x00000001000152c0
- (void).cxx_destruct;	// IMP=0x000000010001a5f0
@property struct __SCPreferences *prefs; // @synthesize prefs=_prefs;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (id)onQueueCopyAppPaths;	// IMP=0x000000010001a52c
- (void)cleanupAppCache:(id)arg1;	// IMP=0x000000010001a24c
- (void)clearCache;	// IMP=0x000000010001a154
- (void)clearUUIDcache;	// IMP=0x000000010001a0c8
- (void)onQueueClearUUIDCache;	// IMP=0x0000000100019fe4
- (id)onQueueCopyPreferredBundleID:(const char *)arg1;	// IMP=0x0000000100019f44
- (id)onQueueCopySigningIdentifierForUUID:(const char *)arg1;	// IMP=0x0000000100019e6c
- (void)copyUUIDsForSigningIdentifier:(id)arg1 executablePath:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100019c5c
- (id)onQueueCopyUUIDsForSigningIdentifier:(id)arg1 executablePath:(id)arg2 allowSynthesis:(_Bool)arg3 uid:(unsigned int)arg4 depth:(unsigned long long)arg5;	// IMP=0x0000000100018ea4
- (id)onQueueCopyUUIDsForSigningIdentifier:(id)arg1 executablePath:(id)arg2 allowSynthesis:(_Bool)arg3 uid:(unsigned int)arg4;	// IMP=0x0000000100018e0c
- (void)updateBundleIDCacheWithPreferredBundleID:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x0000000100018cb0
- (void)updateUUIDCacheWithSynthesizedUUID:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x0000000100018abc
- (void)updateUUIDCacheWithUUIDs:(id)arg1 forBundleIdentifier:(id)arg2;	// IMP=0x00000001000187f8
- (id)copyUUIDCache;	// IMP=0x00000001000187b4
- (void)saveUUIDCache:(id)arg1;	// IMP=0x00000001000186a0
- (void)notifyUUIDCacheChanged;	// IMP=0x000000010001854c
- (id)onQueueAddUUIDsForBundle:(id)arg1 andPlugins:(id)arg2 toArray:(id)arg3;	// IMP=0x000000010001836c
- (id)onQueueAddUUIDsForBundle:(id)arg1 toArray:(id)arg2;	// IMP=0x00000001000181e8
- (id)onQueueExtraSigningIdentifierForUUID:(id)arg1;	// IMP=0x0000000100018020
- (id)onQueueExtraUUIDForSigningIdentifier:(id)arg1;	// IMP=0x0000000100017e58
- (id)onQueueExtraDaemonPathsForSigningIdentifier:(id)arg1;	// IMP=0x0000000100017c04
- (id)onQueueCopyExtraHardcodedPathForSigningIdentifier:(id)arg1;	// IMP=0x0000000100017bdc
- (id)onQueueReadUUIDsForPaths:(id)arg1;	// IMP=0x00000001000179c4
- (void)clearCacheForServiceID:(id)arg1;	// IMP=0x0000000100017804
- (_Bool)onQueueSetRoutes:(id)arg1 forServiceID:(id)arg2 type:(int)arg3;	// IMP=0x00000001000170a8
- (_Bool)onQueueClearDomainDictionariesForServiceID:(id)arg1 type:(int)arg2 interfaceName:(const char *)arg3;	// IMP=0x0000000100016d14
- (_Bool)onQueueSetDomainDictionaries:(id)arg1 forServiceID:(id)arg2 type:(int)arg3 interfaceName:(const char *)arg4;	// IMP=0x0000000100016960
- (void)onQueueClearRedirectedAddresses:(const char *)arg1;	// IMP=0x000000010001678c
- (_Bool)onQueueAddRedirectedAddress:(const struct sockaddr *)arg1 interfaceName:(const char *)arg2;	// IMP=0x00000001000161dc
- (void)onQueueNotifyCacheChanged;	// IMP=0x0000000100016158
- (void)onQueueHandleMessage:(id)arg1;	// IMP=0x0000000100015790
- (void)handleMessage:(id)arg1;	// IMP=0x0000000100015690
- (void)dealloc;	// IMP=0x0000000100015278
- (id)init;	// IMP=0x00000001000151cc
- (id)initWithFirstMessage:(id)arg1;	// IMP=0x0000000100015198

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *name;
@property(readonly) Class superclass;

@end

