/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:40 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/_LSQuery.h>

@class LSDocumentProxy, NSString;

@interface _LSDocumentProxyBindingQuery : _LSQuery {

	BOOL _yieldClaimBindings;
	unsigned char _style;
	LSDocumentProxy* _documentProxy;
	NSString* _handlerRank;

}

@property (assign,nonatomic) BOOL yieldClaimBindings;                               //@synthesize yieldClaimBindings=_yieldClaimBindings - In the implementation block
@property (nonatomic,retain,readonly) LSDocumentProxy * documentProxy;              //@synthesize documentProxy=_documentProxy - In the implementation block
@property (nonatomic,readonly) unsigned char style;                                 //@synthesize style=_style - In the implementation block
@property (nonatomic,copy,readonly) NSString * handlerRank;                         //@synthesize handlerRank=_handlerRank - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(unsigned char)style;
-(NSString *)handlerRank;
-(id)initWithDocumentProxy:(id)arg1 style:(unsigned char)arg2 handlerRank:(id)arg3 ;
-(void)setYieldClaimBindings:(BOOL)arg1 ;
-(LSDocumentProxy *)documentProxy;
-(BOOL)yieldClaimBindings;
-(void)filterOpenRestrictedBindings:(vector<LSBinding, std::__1::allocator<LSBinding> >*)arg1 connection:(id)arg2 context:(LSContext*)arg3 earlyYield:(/*^block*/id)arg4 ;
-(void)_enumerateWithXPCConnection:(id)arg1 block:(/*^block*/id)arg2 ;
-(BOOL)_requiresDatabaseMappingEntitlement;
@end

