/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:40 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/_LSQueryResult.h>

@interface _LSQueryResultWithPropertyList : _LSQueryResult {

	id _propertyList;

}

@property (nonatomic,retain,readonly) id propertyList;              //@synthesize propertyList=_propertyList - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)initWithPropertyList:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)propertyList;
-(id)propertyListWithClass:(Class)arg1 ;
-(id)propertyListWithClass:(Class)arg1 valuesOfClass:(Class)arg2 ;
@end

