/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:40 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface LSAltIconManager : NSObject
+(id)sharedInstance;
-(id)init;
-(id)_getPreferredIconNameForIdentifier:(id)arg1 ;
-(BOOL)isValidAlternateIcon:(id)arg1 forIconsDict:(id)arg2 ;
-(void)_setPreferredIconName:(id)arg1 forIdentifier:(id)arg2 ;
-(BOOL)_setAlternateIconName:(id)arg1 forIdentifier:(id)arg2 withIconsDictionary:(id)arg3 error:(id*)arg4 ;
-(void)clearAlternateNameForBundleIdentifier:(id)arg1 validationDictionary:(id)arg2 ;
-(void)setAlternateIconName:(id)arg1 forIdentifier:(id)arg2 iconsDictionary:(id)arg3 reply:(/*^block*/id)arg4 ;
-(id)alternateIconNameForIdentifier:(id)arg1 error:(id*)arg2 ;
@end

