/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:39 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/LSRecord.h>

@class LSPropertyList, LSExtensionPoint, NSString;

@interface LSExtensionPointRecord : LSRecord

@property (readonly) LSPropertyList * SDKDictionary; 
@property (nonatomic,readonly) LSExtensionPoint * compatibilityObject; 
@property (readonly) NSString * identifier; 
@property (readonly) NSString * name; 
@property (readonly) NSString * version; 
@property (readonly) unsigned platform; 
+(BOOL)supportsSecureCoding;
+(id)enumerator;
+(id)_propertyClasses;
+(id)extensionPointRecordForCurrentProcess;
+(BOOL)isCurrentProcessAnApplicationExtension;
+(id)identifierForCurrentProcess;
+(void)setExtensionPointRecordForCurrentProcess:(id)arg1 ;
-(id)_propertyClassesForCoding;
-(const vector<std::__1::pair<SEL *, void (*)(id, SEL *)>, std::__1::allocator<std::__1::pair<SEL *, void (*)(id, SEL *)> > >*)_resolvingMethods;
-(NSString *)name;
-(NSString *)identifier;
-(NSString *)version;
-(unsigned)platform;
-(id)initWithIdentifier:(id)arg1 error:(id*)arg2 ;
-(id)identifierWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const LSExtensionPointData*)arg4 ;
-(id)nameWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const LSExtensionPointData*)arg4 ;
-(id)versionWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const LSExtensionPointData*)arg4 ;
-(void)_LSRecord_resolve_identifier;
-(void)_LSRecord_resolve_name;
-(void)_LSRecord_resolve_version;
-(id)SDKDictionaryWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const LSExtensionPointData*)arg4 ;
-(void)_LSRecord_resolve_SDKDictionary;
-(void)_detachFromContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const void*)arg4 ;
-(id)_compatibilityObjectWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const void*)arg4 ;
-(id)initWithIdentifier:(id)arg1 platform:(unsigned)arg2 error:(id*)arg3 ;
-(LSPropertyList *)SDKDictionary;
-(unsigned)platformWithContext:(LSContext*)arg1 tableID:(unsigned)arg2 unitID:(unsigned)arg3 unitBytes:(const LSExtensionPointData*)arg4 ;
-(void)_LSRecord_resolve_platform;
@end

