/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:43 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NENetworkAgent.h>

@class NEDNSSettings;

@interface NEDNSSettingsNetworkAgent : NENetworkAgent {

	NEDNSSettings* _settings;

}

@property (retain) NEDNSSettings * settings;              //@synthesize settings=_settings - In the implementation block
+(id)agentType;
+(id)agentDomain;
+(id)agentFromData:(id)arg1 ;
-(NEDNSSettings *)settings;
-(void)setSettings:(NEDNSSettings *)arg1 ;
-(id)copyAgentData;
-(id)agentDescription;
@end

