/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:41 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NetworkExtension-Structs.h>
#import <libobjc.A.dylib/NEPrettyDescription.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol OS_dispatch_queue, OS_xpc_object;
@class NSURL, NSData, NSString, NEFilterAbsoluteVerdict, NSObject, NSUUID, NSMutableArray;

@interface NEFilterFlow : NSObject <NEPrettyDescription, NSSecureCoding, NSCopying> {

	BOOL _isRemediationFlow;
	BOOL _isPaused;
	BOOL _reportAtEnd;
	BOOL _sourceAppIdentifierFromApp;
	int _pid;
	int _epid;
	NSURL* _URL;
	NSData* _sourceAppUniqueIdentifier;
	NSString* _sourceAppIdentifier;
	NSString* _sourceAppVersion;
	long long _direction;
	NSData* _sourceAppAuditToken;
	NEFilterAbsoluteVerdict* _currentVerdict;
	NSObject*<OS_dispatch_queue> _queue;
	NSUUID* _flowUUID;
	NSMutableArray* _savedMessageHandlerQueue;
	unsigned long long _inBytes;
	unsigned long long _outBytes;
	NSData* _crypto_signature;
	NSObject*<OS_xpc_object> _connection;

}

@property (retain) NEFilterAbsoluteVerdict * currentVerdict;               //@synthesize currentVerdict=_currentVerdict - In the implementation block
@property (assign) BOOL isRemediationFlow;                                 //@synthesize isRemediationFlow=_isRemediationFlow - In the implementation block
@property (copy) NSString * sourceAppIdentifier;                           //@synthesize sourceAppIdentifier=_sourceAppIdentifier - In the implementation block
@property (copy) NSString * sourceAppVersion;                              //@synthesize sourceAppVersion=_sourceAppVersion - In the implementation block
@property (copy) NSData * sourceAppUniqueIdentifier;                       //@synthesize sourceAppUniqueIdentifier=_sourceAppUniqueIdentifier - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> queue;                     //@synthesize queue=_queue - In the implementation block
@property (copy) NSURL * URL;                                              //@synthesize URL=_URL - In the implementation block
@property (copy) NSUUID * flowUUID;                                        //@synthesize flowUUID=_flowUUID - In the implementation block
@property (assign) int pid;                                                //@synthesize pid=_pid - In the implementation block
@property (assign) int epid;                                               //@synthesize epid=_epid - In the implementation block
@property (assign) long long direction;                                    //@synthesize direction=_direction - In the implementation block
@property (retain) NSData * sourceAppAuditToken;                           //@synthesize sourceAppAuditToken=_sourceAppAuditToken - In the implementation block
@property (assign) BOOL isPaused;                                          //@synthesize isPaused=_isPaused - In the implementation block
@property (retain) NSMutableArray * savedMessageHandlerQueue;              //@synthesize savedMessageHandlerQueue=_savedMessageHandlerQueue - In the implementation block
@property (assign) BOOL reportAtEnd;                                       //@synthesize reportAtEnd=_reportAtEnd - In the implementation block
@property (assign) BOOL sourceAppIdentifierFromApp;                        //@synthesize sourceAppIdentifierFromApp=_sourceAppIdentifierFromApp - In the implementation block
@property (assign) unsigned long long inBytes;                             //@synthesize inBytes=_inBytes - In the implementation block
@property (assign) unsigned long long outBytes;                            //@synthesize outBytes=_outBytes - In the implementation block
@property (retain) NSData * crypto_signature;                              //@synthesize crypto_signature=_crypto_signature - In the implementation block
@property (retain) NSObject*<OS_xpc_object> connection;                    //@synthesize connection=_connection - In the implementation block
@property (nonatomic,readonly) NSString * identifierString; 
@property (readonly) NSUUID * identifier; 
+(BOOL)supportsSecureCoding;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)description;
-(id)init;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSUUID *)identifier;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
-(BOOL)isPaused;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSObject*<OS_xpc_object>)connection;
-(void)setConnection:(NSObject*<OS_xpc_object>)arg1 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(int)pid;
-(void)setPid:(int)arg1 ;
-(void)setSourceAppIdentifier:(NSString *)arg1 ;
-(NSString *)sourceAppIdentifier;
-(void)setInBytes:(unsigned long long)arg1 ;
-(void)setOutBytes:(unsigned long long)arg1 ;
-(unsigned long long)inBytes;
-(unsigned long long)outBytes;
-(int)epid;
-(long long)direction;
-(void)setDirection:(long long)arg1 ;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(BOOL)isRemediationFlow;
-(NSMutableArray *)savedMessageHandlerQueue;
-(NSString *)identifierString;
-(void)setIsPaused:(BOOL)arg1 ;
-(void)setSavedMessageHandlerQueue:(NSMutableArray *)arg1 ;
-(NSUUID *)flowUUID;
-(NEFilterAbsoluteVerdict *)currentVerdict;
-(BOOL)createDataReply:(id)arg1 controlSocket:(int)arg2 direction:(long long)arg3 verdict:(id)arg4 context:(id)arg5 ;
-(BOOL)createNewFlowReply:(id)arg1 controlSocket:(int)arg2 verdict:(id)arg3 context:(id)arg4 ;
-(void)updateSourceAppInfo:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(BOOL)createDataCompleteReply:(id)arg1 controlSocket:(int)arg2 direction:(long long)arg3 verdict:(id)arg4 context:(id)arg5 ;
-(BOOL)reportAtEnd;
-(void)setReportAtEnd:(BOOL)arg1 ;
-(void)setSourceAppIdentifierFromApp:(BOOL)arg1 ;
-(void)setCrypto_signature:(NSData *)arg1 ;
-(void)setFlowUUID:(NSUUID *)arg1 ;
-(void)setEpid:(int)arg1 ;
-(void)setSourceAppAuditToken:(NSData *)arg1 ;
-(void)setIsRemediationFlow:(BOOL)arg1 ;
-(NSString *)sourceAppVersion;
-(NSData *)sourceAppUniqueIdentifier;
-(NSData *)crypto_signature;
-(BOOL)sourceAppIdentifierFromApp;
-(void)setCurrentVerdict:(NEFilterAbsoluteVerdict *)arg1 ;
-(void)setSourceAppVersion:(NSString *)arg1 ;
-(void)setSourceAppUniqueIdentifier:(NSData *)arg1 ;
-(BOOL)shouldCloseWithVerdict:(id)arg1 ;
-(id)initWithURL:(id)arg1 sourceAppIdentifier:(id)arg2 ;
-(BOOL)updateCurrentVerdictFromDataVerdict:(id)arg1 direction:(long long)arg2 ;
-(NSData *)sourceAppAuditToken;
@end

