/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:41 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NetworkExtension-Structs.h>
#import <NetworkExtension/NEFilterVerdict.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface NEFilterNewFlowVerdict : NEFilterVerdict <NSSecureCoding, NSCopying> {

	BOOL _filterInbound;
	BOOL _filterOutbound;
	long long _statisticsReportFrequency;
	unsigned long long _peekInboundBytes;
	unsigned long long _peekOutboundBytes;

}

@property (assign) BOOL filterInbound;                                //@synthesize filterInbound=_filterInbound - In the implementation block
@property (assign) BOOL filterOutbound;                               //@synthesize filterOutbound=_filterOutbound - In the implementation block
@property (assign) unsigned long long peekInboundBytes;               //@synthesize peekInboundBytes=_peekInboundBytes - In the implementation block
@property (assign) unsigned long long peekOutboundBytes;              //@synthesize peekOutboundBytes=_peekOutboundBytes - In the implementation block
@property (assign) long long statisticsReportFrequency;               //@synthesize statisticsReportFrequency=_statisticsReportFrequency - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)allowVerdict;
+(id)dropVerdict;
+(id)needRulesVerdict;
+(id)remediateVerdictWithRemediationURLMapKey:(id)arg1 remediationButtonTextMapKey:(id)arg2 ;
+(id)pauseVerdict;
+(id)URLAppendStringVerdictWithMapKey:(id)arg1 ;
+(id)filterDataVerdictWithFilterInbound:(BOOL)arg1 peekInboundBytes:(unsigned long long)arg2 filterOutbound:(BOOL)arg3 peekOutboundBytes:(unsigned long long)arg4 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(long long)statisticsReportFrequency;
-(long long)filterAction;
-(void)setStatisticsReportFrequency:(long long)arg1 ;
-(unsigned long long)peekInboundBytes;
-(BOOL)filterInbound;
-(BOOL)filterOutbound;
-(unsigned long long)peekOutboundBytes;
-(void)setFilterInbound:(BOOL)arg1 ;
-(void)setFilterOutbound:(BOOL)arg1 ;
-(void)setPeekInboundBytes:(unsigned long long)arg1 ;
-(void)setPeekOutboundBytes:(unsigned long long)arg1 ;
@end

