/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:42 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NEIKEv2Payload.h>

@class NEIKEv2DHProtocol, NSData;

@interface NEIKEv2KeyExchangePayload : NEIKEv2Payload {

	NEIKEv2DHProtocol* _dh;
	NSData* _dhPublicKey;

}

@property (retain) NEIKEv2DHProtocol * dh;              //@synthesize dh=_dh - In the implementation block
@property (retain) NSData * dhPublicKey;                //@synthesize dhPublicKey=_dhPublicKey - In the implementation block
+(id)copyTypeDescription;
-(id)description;
-(unsigned long long)type;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(void)setDhPublicKey:(NSData *)arg1 ;
-(NSData *)dhPublicKey;
-(void)setDh:(NEIKEv2DHProtocol *)arg1 ;
-(NEIKEv2DHProtocol *)dh;
-(BOOL)hasRequiredFields;
-(BOOL)generatePayloadData;
-(BOOL)parsePayloadData;
@end

