/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:42 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NEIKEv2Payload.h>

@class NSArray;

@interface NEIKEv2TrafficSelectorPayload : NEIKEv2Payload {

	NSArray* _trafficSelectors;

}

@property (retain) NSArray * trafficSelectors;              //@synthesize trafficSelectors=_trafficSelectors - In the implementation block
+(id)copyTypeDescription;
-(id)description;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(void)setTrafficSelectors:(NSArray *)arg1 ;
-(NSArray *)trafficSelectors;
-(BOOL)hasRequiredFields;
-(BOOL)generatePayloadData;
-(BOOL)parsePayloadData;
@end

