/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:43 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NEIKEv2RequestContext.h>

@class NEIKEv2ChildSA;

@interface NEIKEv2NewChildContext : NEIKEv2RequestContext {

	NEIKEv2ChildSA* _childSA;

}

@property (nonatomic,retain) NEIKEv2ChildSA * childSA;              //@synthesize childSA=_childSA - In the implementation block
-(id)description;
-(void)setChildSA:(NEIKEv2ChildSA *)arg1 ;
-(NEIKEv2ChildSA *)childSA;
-(id)initWithChildSA:(id)arg1 ;
@end

