/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:43 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface NELaunchServices : NSObject
+(id)pluginProxyWithIdentifier:(id)arg1 type:(id)arg2 pluginClass:(long long)arg3 extensionPoint:(id)arg4 ;
+(id)pluginClassToExtensionPoint:(long long)arg1 ;
+(id)lookupIdentifier:(id)arg1 plugins:(id*)arg2 ;
+(id)copyLSProxyForUID:(unsigned)arg1 ;
+(id)bundleProxyForIdentifier:(id)arg1 uid:(unsigned)arg2 plugins:(id*)arg3 ;
@end

