/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:43 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NETunnelProvider.h>
#import <libobjc.A.dylib/NSExtensionRequestHandling.h>

@class NEPacketTunnelFlow, NSString;

@interface NEPacketTunnelProvider : NETunnelProvider <NSExtensionRequestHandling> {

	NEPacketTunnelFlow* _packetFlow;

}

@property (retain) NEPacketTunnelFlow * packetFlow;                 //@synthesize packetFlow=_packetFlow - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)requestSocket:(BOOL)arg1 interface:(id)arg2 local:(id)arg3 remote:(id)arg4 completionHandler:(/*^block*/id)arg5 ;
-(NEPacketTunnelFlow *)packetFlow;
-(void)startTunnelWithOptions:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)stopTunnelWithReason:(long long)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)initWithVirtualInterfaceType:(long long)arg1 ;
-(void)cancelTunnelWithError:(id)arg1 ;
-(id)getTunnelInterface;
-(id)createTCPConnectionThroughTunnelToEndpoint:(id)arg1 enableTLS:(BOOL)arg2 TLSParameters:(id)arg3 delegate:(id)arg4 ;
-(id)createUDPSessionThroughTunnelToEndpoint:(id)arg1 fromEndpoint:(id)arg2 ;
-(void)setPacketFlow:(NEPacketTunnelFlow *)arg1 ;
@end

