/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:12:44 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <NetworkExtension/NetworkExtension-Structs.h>
#import <NetworkExtension/NEVPNProtocolIPSec.h>

@class NSString, NEVPNIKEv2SecurityAssociationParameters, NSArray;

@interface NEVPNProtocolIKEv2 : NEVPNProtocolIPSec {

	BOOL _useConfigurationAttributeInternalIPSubnet;
	BOOL _disableMOBIKE;
	BOOL _disableRedirect;
	BOOL _enablePFS;
	BOOL _enableRevocationCheck;
	BOOL _strictRevocationCheck;
	BOOL _enableFallback;
	BOOL _wakeForRekey;
	BOOL _opportunisticPFS;
	BOOL _disableInitialContact;
	int _natKeepAliveOffloadEnable;
	int _natKeepAliveOffloadInterval;
	int _disableMOBIKERetryOnWake;
	long long _deadPeerDetectionRate;
	NSString* _serverCertificateIssuerCommonName;
	NSString* _serverCertificateCommonName;
	long long _certificateType;
	NEVPNIKEv2SecurityAssociationParameters* _IKESecurityAssociationParameters;
	NEVPNIKEv2SecurityAssociationParameters* _childSecurityAssociationParameters;
	long long _minimumTLSVersion;
	long long _maximumTLSVersion;
	unsigned long long _mtu;
	NSString* _pluginType;
	NSArray* _IKESecurityAssociationParametersArray;
	NSArray* _childSecurityAssociationParametersArray;
	NSString* _providerBundleIdentifier;
	long long _tunnelKind;

}

@property (assign) BOOL wakeForRekey;                                                                           //@synthesize wakeForRekey=_wakeForRekey - In the implementation block
@property (readonly) NSString * pluginType;                                                                     //@synthesize pluginType=_pluginType - In the implementation block
@property (retain) NSArray * IKESecurityAssociationParametersArray;                                             //@synthesize IKESecurityAssociationParametersArray=_IKESecurityAssociationParametersArray - In the implementation block
@property (retain) NSArray * childSecurityAssociationParametersArray;                                           //@synthesize childSecurityAssociationParametersArray=_childSecurityAssociationParametersArray - In the implementation block
@property (copy) NSString * providerBundleIdentifier;                                                           //@synthesize providerBundleIdentifier=_providerBundleIdentifier - In the implementation block
@property (assign) int natKeepAliveOffloadEnable;                                                               //@synthesize natKeepAliveOffloadEnable=_natKeepAliveOffloadEnable - In the implementation block
@property (assign) int natKeepAliveOffloadInterval;                                                             //@synthesize natKeepAliveOffloadInterval=_natKeepAliveOffloadInterval - In the implementation block
@property (assign) int disableMOBIKERetryOnWake;                                                                //@synthesize disableMOBIKERetryOnWake=_disableMOBIKERetryOnWake - In the implementation block
@property (assign) BOOL opportunisticPFS;                                                                       //@synthesize opportunisticPFS=_opportunisticPFS - In the implementation block
@property (assign) long long tunnelKind;                                                                        //@synthesize tunnelKind=_tunnelKind - In the implementation block
@property (assign) BOOL disableInitialContact;                                                                  //@synthesize disableInitialContact=_disableInitialContact - In the implementation block
@property (assign) long long deadPeerDetectionRate;                                                             //@synthesize deadPeerDetectionRate=_deadPeerDetectionRate - In the implementation block
@property (copy) NSString * serverCertificateIssuerCommonName;                                                  //@synthesize serverCertificateIssuerCommonName=_serverCertificateIssuerCommonName - In the implementation block
@property (copy) NSString * serverCertificateCommonName;                                                        //@synthesize serverCertificateCommonName=_serverCertificateCommonName - In the implementation block
@property (assign) long long certificateType;                                                                   //@synthesize certificateType=_certificateType - In the implementation block
@property (assign) BOOL useConfigurationAttributeInternalIPSubnet;                                              //@synthesize useConfigurationAttributeInternalIPSubnet=_useConfigurationAttributeInternalIPSubnet - In the implementation block
@property (readonly) NEVPNIKEv2SecurityAssociationParameters * IKESecurityAssociationParameters;                //@synthesize IKESecurityAssociationParameters=_IKESecurityAssociationParameters - In the implementation block
@property (readonly) NEVPNIKEv2SecurityAssociationParameters * childSecurityAssociationParameters;              //@synthesize childSecurityAssociationParameters=_childSecurityAssociationParameters - In the implementation block
@property (assign) BOOL disableMOBIKE;                                                                          //@synthesize disableMOBIKE=_disableMOBIKE - In the implementation block
@property (assign) BOOL disableRedirect;                                                                        //@synthesize disableRedirect=_disableRedirect - In the implementation block
@property (assign) BOOL enablePFS;                                                                              //@synthesize enablePFS=_enablePFS - In the implementation block
@property (assign) BOOL enableRevocationCheck;                                                                  //@synthesize enableRevocationCheck=_enableRevocationCheck - In the implementation block
@property (assign) BOOL strictRevocationCheck;                                                                  //@synthesize strictRevocationCheck=_strictRevocationCheck - In the implementation block
@property (assign) long long minimumTLSVersion;                                                                 //@synthesize minimumTLSVersion=_minimumTLSVersion - In the implementation block
@property (assign) long long maximumTLSVersion;                                                                 //@synthesize maximumTLSVersion=_maximumTLSVersion - In the implementation block
@property (assign) BOOL enableFallback;                                                                         //@synthesize enableFallback=_enableFallback - In the implementation block
@property (assign) unsigned long long mtu;                                                                      //@synthesize mtu=_mtu - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)init;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)providerBundleIdentifier;
-(unsigned long long)mtu;
-(void)setMtu:(unsigned long long)arg1 ;
-(BOOL)checkValidityAndCollectErrors:(id)arg1 ;
-(id)descriptionWithIndent:(int)arg1 options:(unsigned long long)arg2 ;
-(NEVPNIKEv2SecurityAssociationParameters *)IKESecurityAssociationParameters;
-(NEVPNIKEv2SecurityAssociationParameters *)childSecurityAssociationParameters;
-(void)setProviderBundleIdentifier:(NSString *)arg1 ;
-(void)setPluginType:(NSString *)arg1 ;
-(NSString *)pluginType;
-(id)copyLegacyDictionary;
-(id)initWithPluginType:(id)arg1 ;
-(void)setEnableFallback:(BOOL)arg1 ;
-(void)setWakeForRekey:(BOOL)arg1 ;
-(void)setNatKeepAliveOffloadEnable:(int)arg1 ;
-(void)setNatKeepAliveOffloadInterval:(int)arg1 ;
-(id)clone;
-(void)setDeadPeerDetectionRate:(long long)arg1 ;
-(void)setServerCertificateIssuerCommonName:(NSString *)arg1 ;
-(void)setServerCertificateCommonName:(NSString *)arg1 ;
-(void)setCertificateType:(long long)arg1 ;
-(void)setUseConfigurationAttributeInternalIPSubnet:(BOOL)arg1 ;
-(void)setDisableMOBIKE:(BOOL)arg1 ;
-(void)setDisableRedirect:(BOOL)arg1 ;
-(void)setEnablePFS:(BOOL)arg1 ;
-(int)natKeepAliveOffloadEnable;
-(void)setEnableRevocationCheck:(BOOL)arg1 ;
-(BOOL)enableRevocationCheck;
-(void)setStrictRevocationCheck:(BOOL)arg1 ;
-(void)setMinimumTLSVersion:(long long)arg1 ;
-(void)setMaximumTLSVersion:(long long)arg1 ;
-(BOOL)opportunisticPFS;
-(void)setOpportunisticPFS:(BOOL)arg1 ;
-(long long)tunnelKind;
-(void)setTunnelKind:(long long)arg1 ;
-(int)disableMOBIKERetryOnWake;
-(long long)deadPeerDetectionRate;
-(BOOL)disableRedirect;
-(BOOL)wakeForRekey;
-(long long)certificateType;
-(NSArray *)IKESecurityAssociationParametersArray;
-(BOOL)enablePFS;
-(NSArray *)childSecurityAssociationParametersArray;
-(long long)minimumTLSVersion;
-(long long)maximumTLSVersion;
-(int)natKeepAliveOffloadInterval;
-(BOOL)disableMOBIKE;
-(BOOL)strictRevocationCheck;
-(NSString *)serverCertificateCommonName;
-(NSString *)serverCertificateIssuerCommonName;
-(BOOL)disableInitialContact;
-(BOOL)useConfigurationAttributeInternalIPSubnet;
-(BOOL)enableFallback;
-(void)setIKESecurityAssociationParametersArray:(NSArray *)arg1 ;
-(void)setChildSecurityAssociationParametersArray:(NSArray *)arg1 ;
-(void)setDisableMOBIKERetryOnWake:(int)arg1 ;
-(void)setDisableInitialContact:(BOOL)arg1 ;
@end

