/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:24:38 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <DeviceManagement/DMFTaskRequest.h>

@interface DMFFetchRestrictionsRequest : DMFTaskRequest {

	BOOL _includeProfileRestrictions;
	unsigned long long _profileFilterFlags;

}

@property (assign,nonatomic) BOOL includeProfileRestrictions;                    //@synthesize includeProfileRestrictions=_includeProfileRestrictions - In the implementation block
@property (assign,nonatomic) unsigned long long profileFilterFlags;              //@synthesize profileFilterFlags=_profileFilterFlags - In the implementation block
+(BOOL)supportsSecureCoding;
+(Class)whitelistedClassForResultObject;
+(id)permittedPlatforms;
+(BOOL)isPermittedOnSystemConnection;
+(BOOL)isPermittedOnUserConnection;
-(id)init;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(BOOL)includeProfileRestrictions;
-(unsigned long long)profileFilterFlags;
-(void)setIncludeProfileRestrictions:(BOOL)arg1 ;
-(void)setProfileFilterFlags:(unsigned long long)arg1 ;
@end

