/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:43:45 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CEMAssetReference : NSObject {

	int _assettype;
	NSString* _identifier;

}

@property (copy,readonly) NSString * identifier;              //@synthesize identifier=_identifier - In the implementation block
@property (readonly) int assettype;                           //@synthesize assettype=_assettype - In the implementation block
+(id)referenceForIdentifier:(id)arg1 assetschematype:(id)arg2 ;
+(id)referenceForIdentifier:(id)arg1 assettype:(int)arg2 ;
-(NSString *)identifier;
-(id)initWithIdentifier:(id)arg1 assettype:(int)arg2 ;
-(int)assettype;
@end

