//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, _TVSettingsTimeZoneTableViewController;

@protocol _TVSettingsTimeZoneTableViewControllerDelegate <NSObject>
- (void)timeZoneTableViewController:(_TVSettingsTimeZoneTableViewController *)arg1 didSelectCityWithIdentifier:(NSString *)arg2;
@end

