//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PineBoardServices/PBSDisplayMode.h>

@interface PBSDisplayMode (TVSettingsDisplayModeFacade)
- (_Bool)tvs_isEqualResolutionAndRefreshRate:(id)arg1;	// IMP=0x0000000100094d78
- (_Bool)tvs_isCommonResolutionByShowing4KModes:(_Bool)arg1;	// IMP=0x0000000100094ca8
@end

