//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ACAccount, TVSAccountStoreObserver;

@protocol TVSAccountStoreObserverDelegate <NSObject>

@optional
- (void)accountStoreObserver:(TVSAccountStoreObserver *)arg1 didModifyAppleAccount:(ACAccount *)arg2;
- (void)accountStoreObserver:(TVSAccountStoreObserver *)arg1 didModifyPrimaryAppleAccount:(ACAccount *)arg2;
@end

