//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TVSettingsCertificateTrustFacade : NSObject
{
    NSArray *_trustCertificates;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010003a114
- (void).cxx_destruct;	// IMP=0x000000010003a50c
@property(copy, nonatomic) NSArray *trustCertificates; // @synthesize trustCertificates=_trustCertificates;
- (id)_displayNameForCertificate:(struct __SecCertificate *)arg1;	// IMP=0x000000010003a494
- (void)_updateCertificates;	// IMP=0x000000010003a260
- (id)init;	// IMP=0x000000010003a1b0

@end

