//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIActivityIndicatorView;

@interface TVSettingsChooseNetworkHeaderView : UITableViewHeaderFooterView
{
    _Bool _animating;	// 8 = 0x8
    UIActivityIndicatorView *_spinnerView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010009fe04
@property(retain, nonatomic) UIActivityIndicatorView *spinnerView; // @synthesize spinnerView=_spinnerView;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;

@end

