//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class NSArray;

@interface TVSettingsRestrictionsRegionViewController : TSKViewController
{
    NSArray *_filteredSectionIndexTitles;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100034b40
@property(copy, nonatomic) NSArray *filteredSectionIndexTitles; // @synthesize filteredSectionIndexTitles=_filteredSectionIndexTitles;
- (id)_contentFilterRegionFormatter;	// IMP=0x0000000100034a64
- (void)setCountryCode:(id)arg1;	// IMP=0x0000000100034994
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x000000010003498c
- (id)sectionIndexTitlesForTableView:(id)arg1;	// IMP=0x000000010003497c
- (id)loadSettingGroups;	// IMP=0x00000001000340f4

@end

