//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, TVSettingsTapToAddUserManager;

@protocol TVSettingsTapToAddUserManagerDelegate <NSObject>
- (void)tapToAddUserManager:(TVSettingsTapToAddUserManager *)arg1 didFinishWithError:(NSError *)arg2;
- (void)tapToAddUserManagerDidFinish:(TVSettingsTapToAddUserManager *)arg1;
- (void)tapToAddUserManagerDidStart:(TVSettingsTapToAddUserManager *)arg1;
@end

