//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TVSettingsPasscodeDigitViewDelegate-Protocol.h"

@class NSArray, NSString, UIButton;
@protocol TVSettingsIPEntryViewDelegate;

@interface TVSettingsIPEntryView : UIView <TVSettingsPasscodeDigitViewDelegate>
{
    id <TVSettingsIPEntryViewDelegate> _delegate;	// 8 = 0x8
    NSArray *_digitViews;	// 16 = 0x10
    NSArray *_dotViews;	// 24 = 0x18
    NSString *_ipString;	// 32 = 0x20
    UIButton *_doneButton;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000001000d4dc0
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) NSString *ipString; // @synthesize ipString=_ipString;
@property(retain, nonatomic) NSArray *dotViews; // @synthesize dotViews=_dotViews;
@property(retain, nonatomic) NSArray *digitViews; // @synthesize digitViews=_digitViews;
@property(nonatomic) __weak id <TVSettingsIPEntryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)_octetForBlockIndex:(unsigned long long)arg1;	// IMP=0x00000001000d4c9c
- (void)_updateDigitLimits;	// IMP=0x00000001000d4b0c
- (void)doneButton:(id)arg1;	// IMP=0x00000001000d4a68
- (void)passcodeDigitView:(id)arg1 didChangeText:(id)arg2;	// IMP=0x00000001000d4920
- (void)passcodeDigitViewDidResignFirstResponder:(id)arg1;	// IMP=0x00000001000d491c
- (void)passcodeDigitViewDidBecomeFirstResponder:(id)arg1;	// IMP=0x00000001000d4918
@property(copy, nonatomic) NSString *IPAddress;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000d45a0
- (void)layoutSubviews;	// IMP=0x00000001000d4234
- (id)preferredFocusEnvironments;	// IMP=0x00000001000d4214
- (_Bool)canBecomeFocused;	// IMP=0x00000001000d4174
- (id)initWithIPAddress:(id)arg1;	// IMP=0x00000001000d3dbc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

