//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSNumber;
@protocol OS_dispatch_queue;

@interface TVSettingsUsageFacade : NSObject
{
    NSObject<OS_dispatch_queue> *_usage_queue;	// 8 = 0x8
    _Bool _usageUpdateCancelled;	// 16 = 0x10
    NSMutableDictionary *_mediaCache;	// 24 = 0x18
    NSArray *_usageBundlesCache;	// 32 = 0x20
    _Bool _loadingInstalledApps;	// 40 = 0x28
    NSNumber *_usedAppStorage;	// 48 = 0x30
    NSNumber *_totalAppStorage;	// 56 = 0x38
    NSArray *_installedUserApps;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100092be8
@property(copy, nonatomic) NSArray *installedUserApps; // @synthesize installedUserApps=_installedUserApps;
@property(nonatomic) _Bool loadingInstalledApps; // @synthesize loadingInstalledApps=_loadingInstalledApps;
@property(readonly, nonatomic) NSNumber *totalAppStorage; // @synthesize totalAppStorage=_totalAppStorage;
@property(retain, nonatomic) NSNumber *usedAppStorage; // @synthesize usedAppStorage=_usedAppStorage;
- (void)_fetchAppUsageInfo;	// IMP=0x00000001000927f0
- (void)uninstallAppWithProxy:(id)arg1;	// IMP=0x0000000100092644
- (void)dealloc;	// IMP=0x0000000100092570
- (id)init;	// IMP=0x0000000100092440

@end

