//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVSiCloudAccountManagerDelegate-Protocol.h"

@class NSArray, NSString, TVSiCloudAccountManager;

@interface TVSettingsDeviceFacade : NSObject <TVSiCloudAccountManagerDelegate>
{
    NSString *_currentLocale;	// 8 = 0x8
    TVSiCloudAccountManager *_iCloudAccountManager;	// 16 = 0x10
    _Bool _iCloudSharedPhotosEnabled;	// 24 = 0x18
    _Bool _myPhotoStreamEnabled;	// 25 = 0x19
    _Bool _iCloudPhotoLibraryEnabled;	// 26 = 0x1a
    NSArray *_availableNames;	// 32 = 0x20
    NSString *_timeZoneCityName;	// 40 = 0x28
    double _sleepTimeout;	// 48 = 0x30
}

+ (_Bool)automaticallyNotifiesObserversOfCurrentLocale;	// IMP=0x0000000100035138
+ (id)sharedInstance;	// IMP=0x0000000100034b54
- (void).cxx_destruct;	// IMP=0x00000001000362bc
@property(nonatomic) _Bool iCloudPhotoLibraryEnabled; // @synthesize iCloudPhotoLibraryEnabled=_iCloudPhotoLibraryEnabled;
@property(nonatomic) _Bool myPhotoStreamEnabled; // @synthesize myPhotoStreamEnabled=_myPhotoStreamEnabled;
@property(nonatomic) _Bool iCloudSharedPhotosEnabled; // @synthesize iCloudSharedPhotosEnabled=_iCloudSharedPhotosEnabled;
@property(nonatomic) double sleepTimeout; // @synthesize sleepTimeout=_sleepTimeout;
@property(copy, nonatomic) NSString *timeZoneCityName; // @synthesize timeZoneCityName=_timeZoneCityName;
@property(copy, nonatomic) NSArray *availableNames; // @synthesize availableNames=_availableNames;
@property(nonatomic) _Bool updateSoftwareAutomatically;
@property(readonly, nonatomic) _Bool shouldAllowAppOTA;
- (_Bool)setMyPhotoStreamEnabled:(_Bool)arg1 error:(id *)arg2;	// IMP=0x000000010003609c
- (_Bool)setICloudPhotoLibraryEnabled:(_Bool)arg1 error:(id *)arg2;	// IMP=0x0000000100036004
- (_Bool)setICloudSharedPhotosEnabled:(_Bool)arg1 error:(id *)arg2;	// IMP=0x0000000100035f6c
@property(readonly, nonatomic) _Bool myPhotoStreamAvailable;
- (void)iCloudAccountManager:(id)arg1 didModifyActiveAccount:(id)arg2;	// IMP=0x0000000100035e44
@property(readonly, nonatomic, getter=isSleepDisabledByProfile) _Bool sleepDisabledByProfile;
- (void)_updateSleepTimeoutValue;	// IMP=0x0000000100035c1c
- (id)cityNameForCityID:(id)arg1;	// IMP=0x0000000100035b3c
@property(copy, nonatomic) NSString *timeZoneCityID;
@property(nonatomic, getter=isAutomaticTimeZoneSelectionEnabled) _Bool automaticTimeZoneSelectionEnabled;
@property(readonly, copy, nonatomic) NSArray *availableLocales;
- (void)_updateCurrentLocale;	// IMP=0x0000000100035860
@property(copy, nonatomic) NSString *currentLocale;
@property(copy, nonatomic) NSString *systemLanguage;
@property(nonatomic) _Bool shouldSendAppAnalytics;
@property(readonly, nonatomic) _Bool isSendAppAnalyticsLockedDown;
@property(nonatomic) _Bool shouldSendDataToApple;
@property(readonly, nonatomic) _Bool isSendDataToAppleLockedDown;
- (id)internetConfigurationSummary;	// IMP=0x000000010003546c
@property(readonly, copy, nonatomic) NSString *HDMIFirmwareVersion;
@property(readonly, copy, nonatomic) NSString *systemSoftwareVersion;
@property(readonly, copy, nonatomic) NSString *serialNumber;
@property(readonly, copy, nonatomic) NSString *marketingNumber;
@property(readonly, copy, nonatomic) NSString *modelDescription;
@property(readonly, nonatomic, getter=isNameModificationAllowed) _Bool nameModificationAllowed;
@property(copy, nonatomic) NSString *name;
- (id)init;	// IMP=0x0000000100034d28

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

