//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsNotificationsViewController : TSKViewController
{
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000259f0
- (id)loadSettingGroups;	// IMP=0x00000001000257f4
- (void)dealloc;	// IMP=0x000000010002576c
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000256d8

@end

