//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, TVSettingsUser, TVSettingsUserProfileFacade;

@interface TVSettingsUserAppleIDServiceViewController : TSKViewController <UIGestureRecognizerDelegate>
{
    TVSettingsUser *_user;	// 8 = 0x8
    long long _serviceType;	// 16 = 0x10
    TVSettingsUserProfileFacade *_profileFacade;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010003f360
@property(retain, nonatomic) TVSettingsUserProfileFacade *profileFacade; // @synthesize profileFacade=_profileFacade;
@property(nonatomic) long long serviceType; // @synthesize serviceType=_serviceType;
@property(retain, nonatomic) TVSettingsUser *user; // @synthesize user=_user;
- (void)_menuPressed:(id)arg1;	// IMP=0x000000010003f2ac
- (void)_presentGameCenterAboutFriends:(id)arg1;	// IMP=0x000000010003f128
- (id)_gameCenterOptions;	// IMP=0x000000010003eb40
- (void)_signOut:(id)arg1;	// IMP=0x000000010003e694
- (void)_signIn:(id)arg1;	// IMP=0x000000010003e66c
- (id)_appleIdOptions;	// IMP=0x000000010003dd38
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x000000010003dce4
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010003dbfc
- (id)loadSettingGroups;	// IMP=0x000000010003db2c
- (void)viewDidLoad;	// IMP=0x000000010003da60
- (void)dealloc;	// IMP=0x000000010003d9f4
- (id)initWithUser:(id)arg1 serviceType:(long long)arg2;	// IMP=0x000000010003d904

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

