//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "AKAppleIDAuthenticationInAppContextDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, TVSettingsAccountsFacade, UITapGestureRecognizer;

@interface TVSettingsGameCenterAccountViewController : TSKViewController <AKAppleIDAuthenticationInAppContextDelegate, UIGestureRecognizerDelegate>
{
    _Bool _authenticationInProgress;	// 8 = 0x8
    UITapGestureRecognizer *_menuGestureRecognizer;	// 16 = 0x10
    _Bool _signOutInProgress;	// 24 = 0x18
    TVSettingsAccountsFacade *_accountsFacade;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100018544
@property(retain, nonatomic) TVSettingsAccountsFacade *accountsFacade; // @synthesize accountsFacade=_accountsFacade;
- (void)contextDidDismissLoginAlertController:(id)arg1;	// IMP=0x000000010001851c
- (void)contextWillDismissLoginAlertController:(id)arg1;	// IMP=0x0000000100018518
- (void)contextDidPresentLoginAlertController:(id)arg1;	// IMP=0x00000001000184e0
- (void)_presentAboutFriends:(id)arg1;	// IMP=0x000000010001835c
- (void)_updateSignInItem:(id)arg1 value:(id)arg2;	// IMP=0x0000000100017fc0
- (void)_presentError:(id)arg1;	// IMP=0x0000000100017d20
- (void)_signOut:(id)arg1;	// IMP=0x00000001000179f8
- (void)_resetAuthenticationInProgressState;	// IMP=0x0000000100017900
- (void)_signIn:(id)arg1;	// IMP=0x0000000100017280
@property(getter=isAuthenticationInProgress) _Bool authenticationInProgress;
- (id)loadSettingGroups;	// IMP=0x0000000100016a44
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x00000001000169e0
- (id)init;	// IMP=0x00000001000169a8
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100016970
- (id)initWithStyle:(long long)arg1;	// IMP=0x0000000100016938
- (id)initWithAccountsFacade:(id)arg1;	// IMP=0x0000000100016798

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

