//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TVCSTapToSetupManagerDelegate-Protocol.h"

@class NSString, TVCSTapToSetupManager, TVSettingsTapToSetupView;
@protocol TVSettingsTapToSetupViewControllerDelegate;

@interface TVSettingsTapToSetupViewController : TSKViewController <TVCSTapToSetupManagerDelegate>
{
    id <TVSettingsTapToSetupViewControllerDelegate> _delegate;	// 8 = 0x8
    TVSettingsTapToSetupView *_tapToSetupView;	// 16 = 0x10
    TVCSTapToSetupManager *_tapToSetupManager;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000abcd8
@property(retain, nonatomic) TVCSTapToSetupManager *tapToSetupManager; // @synthesize tapToSetupManager=_tapToSetupManager;
@property(retain, nonatomic) TVSettingsTapToSetupView *tapToSetupView; // @synthesize tapToSetupView=_tapToSetupView;
@property(nonatomic) __weak id <TVSettingsTapToSetupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_presentAlertController:(id)arg1;	// IMP=0x00000001000abb6c
- (void)tapToSetupManager:(id)arg1 presentErrorAlert:(id)arg2;	// IMP=0x00000001000abb5c
- (void)tapToSetupManager:(id)arg1 didFailSetupWithError:(id)arg2;	// IMP=0x00000001000ab820
- (void)tapToSetupManagerDidFinishSetup:(id)arg1 deviceInfo:(id)arg2;	// IMP=0x00000001000ab5c0
- (void)tapToSetupManager:(id)arg1 didBeginSetupWithDeviceName:(id)arg2 isNewFlow:(_Bool)arg3;	// IMP=0x00000001000ab4cc
- (void)tapToSetupManagerDidPromptToBeginSetup:(id)arg1;	// IMP=0x00000001000ab3b0
- (id)presentingControllerForTTSUManager:(id)arg1;	// IMP=0x00000001000ab3ac
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000ab354
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000ab2fc
- (void)viewDidLoad;	// IMP=0x00000001000ab108
- (void)dealloc;	// IMP=0x00000001000ab09c
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000ab01c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

