//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsOSUpdateSeedViewController : TSKViewController
{
}

- (id)_descriptionForConfiguration:(id)arg1;	// IMP=0x00000001000278a0
- (void)_updateVPNItem:(id)arg1;	// IMP=0x00000001000276f8
- (void)_updateAppleConnectItem:(id)arg1;	// IMP=0x0000000100027594
- (void)_toggleAdvancedSettingsItems:(id)arg1;	// IMP=0x000000010002754c
- (void)_setShouldShowAdvancedSettings:(_Bool)arg1;	// IMP=0x0000000100027460
- (_Bool)_shouldShowAdvancedSettings;	// IMP=0x00000001000273a4
- (void)_clearNumericSettingItem:(id)arg1;	// IMP=0x0000000100027384
- (id)loadSettingGroups;	// IMP=0x000000010002635c
- (void)viewDidLoad;	// IMP=0x0000000100026290

@end

