//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class NSArray, TVPAudioRoute, TVPAudioRoutingController;

@interface TVSettingsAudioRouteViewController : TSKViewController
{
    TVPAudioRoutingController *_routingController;	// 8 = 0x8
    TVPAudioRoute *_recentlySelectedRoute;	// 16 = 0x10
    NSArray *_routes;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000b1ef0
- (id)_identifierForRoute:(id)arg1;	// IMP=0x00000001000b1dd0
- (void)_selectRoute:(id)arg1;	// IMP=0x00000001000b1d68
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;	// IMP=0x00000001000b1a78
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000b1880
- (id)loadSettingGroups;	// IMP=0x00000001000b14ac
- (void)viewDidLoad;	// IMP=0x00000001000b13f8
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000b1378

@end

