//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class NSString, TVSettingsDiagnosticLogsFacade;

@interface TVSettingsPrivacyLogFileViewController : TSKViewController
{
    _Bool _allowViewing;	// 8 = 0x8
    NSString *_logPath;	// 16 = 0x10
    TVSettingsDiagnosticLogsFacade *_logsFacade;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000c8684
@property(nonatomic) _Bool allowViewing; // @synthesize allowViewing=_allowViewing;
@property(retain, nonatomic) TVSettingsDiagnosticLogsFacade *logsFacade; // @synthesize logsFacade=_logsFacade;
@property(copy, nonatomic) NSString *logPath; // @synthesize logPath=_logPath;
- (void)_deleteItem:(id)arg1;	// IMP=0x00000001000c81dc
- (void)_airDropItem:(id)arg1;	// IMP=0x00000001000c7ee0
- (void)_viewItem:(id)arg1;	// IMP=0x00000001000c7cdc
- (id)loadSettingGroups;	// IMP=0x00000001000c7710

@end

