//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVSettingsTCCFacade.h"

@interface TVSettingsUserAccessFacade : TVSettingsTCCFacade
{
    _Bool _enabledOnDevice;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00000001000e4460
@property(nonatomic, getter=isEnabledOnDevice) _Bool enabledOnDevice; // @synthesize enabledOnDevice=_enabledOnDevice;
- (_Bool)setAllowAccess:(_Bool)arg1 forInfo:(id)arg2;	// IMP=0x00000001000e4b14
- (id)fetchInfoMapping;	// IMP=0x00000001000e462c

@end

