//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TVPhotoAsset, TVPhotoCollection, TVSettingsPhotoCollectionGroupViewController;

@protocol TVSettingsPhotoCollectionGroupViewControllerDelegate <NSObject>

@optional
- (void)controller:(TVSettingsPhotoCollectionGroupViewController *)arg1 didSelectAsset:(TVPhotoAsset *)arg2 inCollection:(TVPhotoCollection *)arg3;
@end

