//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsAppearanceViewController : TSKViewController
{
}

- (void)_promptUserToEnablePermissions;	// IMP=0x000000010006cc78
- (void)selectItem:(id)arg1;	// IMP=0x000000010006cbd0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010006cb18
- (id)loadSettingGroups;	// IMP=0x000000010006c6a4
- (void)dealloc;	// IMP=0x000000010006c61c
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010006c588

@end

