//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, TVSettingsHighlightView, UIImageView, UILabel;
@protocol TVSettingsPasscodeDigitViewDelegate;

@interface TVSettingsPasscodeDigitView : UIView
{
    _Bool _showDigit;	// 8 = 0x8
    double _fontSize;	// 16 = 0x10
    unsigned long long _maxDigitValue;	// 24 = 0x18
    id <TVSettingsPasscodeDigitViewDelegate> _delegate;	// 32 = 0x20
    double _highlightProgress;	// 40 = 0x28
    UIView *_clippingView;	// 48 = 0x30
    UILabel *_label;	// 56 = 0x38
    TVSettingsHighlightView *_highlight;	// 64 = 0x40
    UIImageView *_bulletView;	// 72 = 0x48
    UIImageView *_upArrowView;	// 80 = 0x50
    UIImageView *_downArrowView;	// 88 = 0x58
    NSArray *_recognizers;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00000001000c4574
@property(retain, nonatomic) NSArray *recognizers; // @synthesize recognizers=_recognizers;
@property(retain, nonatomic) UIImageView *downArrowView; // @synthesize downArrowView=_downArrowView;
@property(retain, nonatomic) UIImageView *upArrowView; // @synthesize upArrowView=_upArrowView;
@property(retain, nonatomic) UIImageView *bulletView; // @synthesize bulletView=_bulletView;
@property(retain, nonatomic) TVSettingsHighlightView *highlight; // @synthesize highlight=_highlight;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIView *clippingView; // @synthesize clippingView=_clippingView;
@property(nonatomic) double highlightProgress; // @synthesize highlightProgress=_highlightProgress;
@property(nonatomic) __weak id <TVSettingsPasscodeDigitViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool showDigit; // @synthesize showDigit=_showDigit;
@property(nonatomic) unsigned long long maxDigitValue; // @synthesize maxDigitValue=_maxDigitValue;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (id)hiddenDigitImage;	// IMP=0x00000001000c410c
- (id)arrowImage:(_Bool)arg1;	// IMP=0x00000001000c3efc
- (void)downGesture:(id)arg1;	// IMP=0x00000001000c3ddc
- (void)upGesture:(id)arg1;	// IMP=0x00000001000c3cd0
@property(copy, nonatomic) NSString *text;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000c3a2c
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000c38f4
- (_Bool)canBecomeFocused;	// IMP=0x00000001000c38ec
- (void)layoutSubviews;	// IMP=0x00000001000c3674
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000c2f78

@end

