//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsSetupViewController : TSKViewController
{
}

- (void)_handleRestart;	// IMP=0x00000001000766a8
- (void)_handleResetAllSettingsResultWithError:(id)arg1;	// IMP=0x0000000100076460
- (void)_showFailureWithText:(id)arg1;	// IMP=0x000000010007630c
- (void)_showConfirmRestore;	// IMP=0x0000000100075ffc
- (void)_showConfirmReset;	// IMP=0x0000000100075bec
- (id)_resetViewController;	// IMP=0x0000000100075850
- (id)loadSettingGroups;	// IMP=0x0000000100074fd8

@end

