//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsCertificateTrustViewController : TSKViewController
{
}

- (void)_toggleTrust:(id)arg1;	// IMP=0x00000001000cb190
- (id)loadSettingGroups;	// IMP=0x00000001000cade0

@end

