//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

@class NSString;

@interface TVSettingsPrivacyPowerLogViewController : TSKViewController
{
    NSString *_logPath;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010001f47c
@property(copy, nonatomic) NSString *logPath; // @synthesize logPath=_logPath;
- (id)loadSettingGroups;	// IMP=0x000000010001f138

@end

