//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface TVSettingsOverscanViewController : UIViewController
{
}

- (id)title;	// IMP=0x00000001000805ac
- (void)loadView;	// IMP=0x000000010008033c

@end

