//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "PBSExternalControlIRLearningManagerDelegate-Protocol.h"

@class NSSet, NSString, NSUUID, PBSExternalControlIRLearningConfiguration, PBSExternalControlIRLearningManager, UIButton, UIImageView, UILabel, UIProgressView, UIStackView, UITapGestureRecognizer;

@interface TVSettingsLearnRemoteViewController : UIViewController <PBSExternalControlIRLearningManagerDelegate>
{
    struct {
        unsigned int startLearningAttemptCount:4;
        unsigned int shouldCompleteOnViewDidAppear:1;
        unsigned int didFailFromError:1;
        unsigned int didFailFromInactivity:1;
        unsigned int shouldLearnNextActionOnButtonRelease:1;
    } _flags;	// 8 = 0x8
    PBSExternalControlIRLearningConfiguration *_configuration;	// 16 = 0x10
    CDUnknownBlockType _completionHandler;	// 24 = 0x18
    UILabel *_titleLabel;	// 32 = 0x20
    UILabel *_instructionLabel;	// 40 = 0x28
    UILabel *_bottomTextLabel;	// 48 = 0x30
    UILabel *_activityLabel;	// 56 = 0x38
    UIProgressView *_progressView;	// 64 = 0x40
    UIImageView *_buttonImageView;	// 72 = 0x48
    UIStackView *_learningStackView;	// 80 = 0x50
    UIStackView *_learningHeaderStackView;	// 88 = 0x58
    UIStackView *_learningProgressStackView;	// 96 = 0x60
    UIButton *_focusButton;	// 104 = 0x68
    UITapGestureRecognizer *_leftTapGestureRecognizer;	// 112 = 0x70
    UITapGestureRecognizer *_rightTapGestureRecognizer;	// 120 = 0x78
    PBSExternalControlIRLearningManager *_learningManager;	// 128 = 0x80
    NSSet *_learnedActions;	// 136 = 0x88
    NSUUID *_learnedDeviceUUID;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x00000001000a5cd0
@property(retain, nonatomic) NSUUID *learnedDeviceUUID; // @synthesize learnedDeviceUUID=_learnedDeviceUUID;
@property(copy, nonatomic) NSSet *learnedActions; // @synthesize learnedActions=_learnedActions;
@property(retain, nonatomic) PBSExternalControlIRLearningManager *learningManager; // @synthesize learningManager=_learningManager;
@property(retain, nonatomic) UITapGestureRecognizer *rightTapGestureRecognizer; // @synthesize rightTapGestureRecognizer=_rightTapGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *leftTapGestureRecognizer; // @synthesize leftTapGestureRecognizer=_leftTapGestureRecognizer;
@property(retain, nonatomic) UIButton *focusButton; // @synthesize focusButton=_focusButton;
@property(retain, nonatomic) UIStackView *learningProgressStackView; // @synthesize learningProgressStackView=_learningProgressStackView;
@property(retain, nonatomic) UIStackView *learningHeaderStackView; // @synthesize learningHeaderStackView=_learningHeaderStackView;
@property(retain, nonatomic) UIStackView *learningStackView; // @synthesize learningStackView=_learningStackView;
@property(retain, nonatomic) UIImageView *buttonImageView; // @synthesize buttonImageView=_buttonImageView;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(retain, nonatomic) UILabel *bottomTextLabel; // @synthesize bottomTextLabel=_bottomTextLabel;
@property(retain, nonatomic) UILabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) PBSExternalControlIRLearningConfiguration *configuration; // @synthesize configuration=_configuration;
- (id)_imageForAction:(int)arg1;	// IMP=0x00000001000a58f4
- (void)_learnNextAction:(id)arg1;	// IMP=0x00000001000a5854
- (void)_learnPreviousAction:(id)arg1;	// IMP=0x00000001000a57b4
- (void)_updateProgressViewWithProgress:(double)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000a571c
- (void)_hideProgressView;	// IMP=0x00000001000a5694
- (void)irLearningManager:(id)arg1 didFinishLearningAction:(int)arg2;	// IMP=0x00000001000a5208
- (void)irLearningManager:(id)arg1 didCompleteLearningAction:(int)arg2 withResult:(_Bool)arg3 error:(id)arg4;	// IMP=0x00000001000a4c54
- (void)irLearningManager:(id)arg1 didLearnAction:(int)arg2 withProgress:(double)arg3;	// IMP=0x00000001000a4b00
- (void)irLearningManager:(id)arg1 willStartLearningAction:(int)arg2;	// IMP=0x00000001000a4790
- (void)irLearningManagerDidCancel:(id)arg1;	// IMP=0x00000001000a478c
- (void)irLearningManager:(id)arg1 didSaveLearnedActions:(id)arg2 forDeviceWithUUID:(id)arg3;	// IMP=0x00000001000a44b0
- (void)irLearningManager:(id)arg1 didFailToStartLearningWithError:(id)arg2;	// IMP=0x00000001000a429c
- (id)preferredFocusEnvironments;	// IMP=0x00000001000a4214
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000a4098
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000a3ea0
- (void)viewDidLoad;	// IMP=0x00000001000a2a64
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000a2980

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

