//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVSettingKit/TSKViewController.h>

#import "TSKSettingItemEditingController-Protocol.h"

@class NSString, TSKSettingItem;
@protocol TSKSettingItemEditingControllerDelegate;

@interface TVSettingsBluetoothInfoViewController : TSKViewController <TSKSettingItemEditingController>
{
    TSKSettingItem *_editingItem;	// 8 = 0x8
    id <TSKSettingItemEditingControllerDelegate> _editingDelegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100088fb0
@property(nonatomic) __weak id <TSKSettingItemEditingControllerDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
@property(retain, nonatomic) TSKSettingItem *editingItem; // @synthesize editingItem=_editingItem;
- (id)_bluetoothDevice;	// IMP=0x0000000100088eb0
- (void)_connectDevice:(id)arg1;	// IMP=0x0000000100088e18
- (void)_unpairDevice:(id)arg1;	// IMP=0x0000000100088948
- (void)_disconnectDevice:(id)arg1;	// IMP=0x00000001000888b0
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100088730
- (id)loadSettingGroups;	// IMP=0x00000001000876d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

