/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:10:38 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSString;

@interface MCAnalyticsEvent : NSObject {

	NSString* _eventKey;
	/*^block*/id _eventPayloadBuilder;

}
-(id)initWithEventKey:(id)arg1 eventPayloadBuilder:(/*^block*/id)arg2 ;
-(void)sendEvent;
-(void)sendEventLazy;
@end

