/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:10:38 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface MCHacks : NSObject
+(id)sharedHacks;
-(id)quantizedGracePeriodInSeconds:(id)arg1 ;
-(id)quantizedAutoLockInSeconds:(id)arg1 ;
-(BOOL)sanitizedProfileSignerCertificateChainIsAllowedToWriteDefaults:(id)arg1 ;
-(BOOL)sanitizedProfileSignerCertificateChainIsAllowedToInstallUnsupportedPayload:(id)arg1 ;
-(BOOL)sanitizedProfileSignerCertificateChainIsAllowedToInstallSupervisedRestrictionsOnUnsupervisedDevices:(id)arg1 ;
-(BOOL)_applyHeuristicsToRestrictions:(id)arg1 forProfile:(id)arg2 outError:(id*)arg3 ;
-(id)permittedAutoLockNumbers;
-(id)_permittedGracePeriodNumbers;
-(id)_selectLargestNumberFromSortedArray:(id)arg1 equalToOrLessThanNumber:(id)arg2 ;
-(BOOL)isJapanSKU;
-(id)profileTrustEvaluators;
-(void)_applyServerSideChangesWithOldRestrictions:(id)arg1 newRestrictions:(id)arg2 oldEffectiveUserSettings:(id)arg3 newEffectiveUserSettings:(id)arg4 ;
-(void)_applyImpliedSettingsToSettingsDictionary:(id)arg1 currentSettings:(id)arg2 restrictions:(id)arg3 ;
-(void)_applyHeuristicsToEffectiveUserSettings:(id)arg1 ;
-(void)_applyMandatorySettingsToEffectiveUserSettings:(id)arg1 ;
-(void)_applyHeuristicsToGranfatheredRestrictionPayloadKeys:(id)arg1 ;
-(void)_setRequriesEncryptedBackupInLockdownWithEffectiveUserSettings:(id)arg1 ;
-(id)_deviceSpecificDefaultSettings;
-(void)_sendChangeNotificationsBasedOnDefaultsAdditionByDomain:(id)arg1 ;
-(void)_sendChangeNotificationsBasedOnDefaultsRemovalByDomain:(id)arg1 ;
-(BOOL)isGreenTea;
-(BOOL)isSetupBuddyDone;
@end

