/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:10:37 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface MCLazyInitializationUtilities : NSObject
+(void)loadBundleAtURL:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
+(void)loadNSBundleAtURL:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
+(void)initPowerlogControl;
+(void)initCoreGraphics;
+(void)initImageIO;
+(void)initCoreText;
+(void)initLoggingSupport;
+(void)initSetupAssistant;
+(void)initSpringBoardServices;
@end

