/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:10:38 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <ManagedConfiguration/MCPayload.h>

@class NSArray;

@interface MCNetworkUsageRulesPayload : MCPayload {

	NSArray* _applicationRules;
	NSArray* _SIMRules;

}

@property (nonatomic,copy) NSArray * applicationRules;                     //@synthesize applicationRules=_applicationRules - In the implementation block
@property (setter=IMRules,nonatomic,copy) NSArray * SIMRules;              //@synthesize SIMRules=_SIMRules - In the implementation block
+(id)typeStrings;
+(id)localizedSingularForm;
+(id)localizedPluralForm;
-(id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3 ;
-(id)stubDictionary;
-(id)payloadDescriptionKeyValueSections;
-(id)verboseDescription;
-(id)installationWarnings;
-(NSArray *)applicationRules;
-(NSArray *)SIMRules;
-(void)setApplicationRules:(NSArray *)arg1 ;
-(void)setSIMRules:(NSArray *)arg1 ;
@end

