/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, November 10, 2020 at 10:10:38 PM Mountain Standard Time
                       * Operating System: Version 14.2 (Build 18K57)
                       * Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <ManagedConfiguration/MCCertificatePayload.h>

@class NSString, NSArray, NSData, NSDictionary;

@interface MCSCEPPayload : MCCertificatePayload {

	NSString* _URLString;
	NSString* _CAInstanceName;
	NSString* _challenge;
	NSArray* _subject;
	unsigned long long _keySize;
	int _usageFlags;
	NSData* _CAFingerprint;
	NSArray* _CACaps;
	NSDictionary* _subjectAltName;
	unsigned long long _retries;
	unsigned long long _retryDelay;

}

@property (nonatomic,retain,readonly) NSString * URLString;                       //@synthesize URLString=_URLString - In the implementation block
@property (nonatomic,retain,readonly) NSString * CAInstanceName;                  //@synthesize CAInstanceName=_CAInstanceName - In the implementation block
@property (nonatomic,retain,readonly) NSData * CAFingerprint;                     //@synthesize CAFingerprint=_CAFingerprint - In the implementation block
@property (nonatomic,retain,readonly) NSArray * CACaps;                           //@synthesize CACaps=_CACaps - In the implementation block
@property (nonatomic,retain,readonly) NSString * challenge;                       //@synthesize challenge=_challenge - In the implementation block
@property (nonatomic,retain,readonly) NSArray * subject;                          //@synthesize subject=_subject - In the implementation block
@property (nonatomic,readonly) unsigned long long keySize;                        //@synthesize keySize=_keySize - In the implementation block
@property (nonatomic,readonly) int usageFlags;                                    //@synthesize usageFlags=_usageFlags - In the implementation block
@property (nonatomic,retain,readonly) NSDictionary * subjectAltName;              //@synthesize subjectAltName=_subjectAltName - In the implementation block
@property (nonatomic,readonly) unsigned long long retries;                        //@synthesize retries=_retries - In the implementation block
@property (nonatomic,readonly) unsigned long long retryDelay;                     //@synthesize retryDelay=_retryDelay - In the implementation block
+(id)typeStrings;
+(id)localizedSingularForm;
+(id)localizedPluralForm;
-(int)usageFlags;
-(NSArray *)subject;
-(id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id*)arg3 ;
-(id)stubDictionary;
-(id)payloadDescriptionKeyValueSections;
-(id)verboseDescription;
-(NSString *)URLString;
-(NSString *)challenge;
-(BOOL)isIdentity;
-(BOOL)isRoot;
-(NSString *)CAInstanceName;
-(unsigned long long)keySize;
-(NSData *)CAFingerprint;
-(NSArray *)CACaps;
-(NSDictionary *)subjectAltName;
-(unsigned long long)retries;
-(unsigned long long)retryDelay;
@end

