/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:45:29 AM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /System/Library/PrivateFrameworks/TVSystemMenuUI.framework/TVSystemMenuUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>
#import <TVSystemMenuUI/TVSMModuleContentViewController.h>

@protocol TVSMModuleContentViewControllerDelegate;
@class UIImage, NSString, NSPersonNameComponents, TVSMMonogramView;

@interface TVSMMonogramViewController : UIViewController <TVSMModuleContentViewController> {

	BOOL _showSelection;
	id<TVSMModuleContentViewControllerDelegate> _delegate;
	UIImage* _image;
	NSString* _titleText;
	NSPersonNameComponents* _nameComponents;
	TVSMMonogramView* _monogramView;

}

@property (nonatomic,retain) UIImage * image;                                                          //@synthesize image=_image - In the implementation block
@property (nonatomic,copy) NSString * titleText;                                                       //@synthesize titleText=_titleText - In the implementation block
@property (nonatomic,copy) NSPersonNameComponents * nameComponents;                                    //@synthesize nameComponents=_nameComponents - In the implementation block
@property (assign,nonatomic) BOOL showSelection;                                                       //@synthesize showSelection=_showSelection - In the implementation block
@property (nonatomic,readonly) TVSMMonogramView * monogramView;                                        //@synthesize monogramView=_monogramView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<TVSMModuleContentViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id<TVSMModuleContentViewControllerDelegate>)delegate;
-(void)setDelegate:(id<TVSMModuleContentViewControllerDelegate>)arg1 ;
-(UIImage *)image;
-(void)setImage:(UIImage *)arg1 ;
-(NSString *)titleText;
-(void)setTitleText:(NSString *)arg1 ;
-(NSPersonNameComponents *)nameComponents;
-(void)setNameComponents:(NSPersonNameComponents *)arg1 ;
-(void)loadView;
-(void)_buttonPressed:(id)arg1 ;
-(TVSMMonogramView *)monogramView;
-(void)setShowSelection:(BOOL)arg1 ;
-(BOOL)showSelection;
@end

