/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:45:29 AM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /System/Library/PrivateFrameworks/TVSystemMenuUI.framework/TVSystemMenuUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UICollectionViewCell.h>

@class TVLockupView;

@interface TVSMLockupContainingCollectionViewCell : UICollectionViewCell {

	TVLockupView* _lockupView;

}

@property (nonatomic,retain) TVLockupView * lockupView;              //@synthesize lockupView=_lockupView - In the implementation block
-(void)setSelected:(BOOL)arg1 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(id)preferredLayoutAttributesFittingAttributes:(id)arg1 ;
-(TVLockupView *)lockupView;
-(void)setLockupView:(TVLockupView *)arg1 ;
@end

