/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:45:29 AM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /System/Library/PrivateFrameworks/TVSystemMenuUI.framework/TVSystemMenuUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TVSystemMenuUI/TVSMModule.h>

@protocol TVSMModuleDelegate;
@class NSBundle, NSString, NSArray;

@interface TVSMCollectionModule : NSObject {
    
}

@property (nonatomic,readonly) UIViewController* contentViewController;
@property (nonatomic,readonly) UIViewController* expandedContentViewController;
@property (nonatomic,readonly) NSArray * childModules; 
+(long long)buttonStyle;
-(id)init;
-(long long)type;
-(id)delegate;
-(void)setDelegate:(id)arg1 ;
-(NSBundle *)bundle;
-(BOOL)dismissAfterAction;
-(NSArray *)childModules;
-(void)contentModuleViewControllerDidTriggerAction:(id)arg1 ;
-(void)handleActionForChildModuleAtIndex:(unsigned long long)arg1 ;
@end

